<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daehyeog Lee">
<meta name="dcterms.date" content="2023-01-10">

<title>Chapter 12. Factorial ANOVA (GLM 3)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="chapter_12_files/libs/clipboard/clipboard.min.js"></script>
<script src="chapter_12_files/libs/quarto-html/quarto.js"></script>
<script src="chapter_12_files/libs/quarto-html/popper.min.js"></script>
<script src="chapter_12_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="chapter_12_files/libs/quarto-html/anchor.min.js"></script>
<link href="chapter_12_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="chapter_12_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="chapter_12_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="chapter_12_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="chapter_12_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Chapter 12. Factorial ANOVA (GLM 3)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Daehyeog Lee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 10, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">January 22, 2024</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="what-will-this-chapter-tell-me" class="level2">
<h2 class="anchored" data-anchor-id="what-will-this-chapter-tell-me">12.1. What will this chapter tell me?</h2>
<p>Factorial ANOVA can deal with two predictor variables, while one-way ANOVA can’t.</p>
</section>
<section id="theory-of-factorial-anova-independent-design" class="level2">
<h2 class="anchored" data-anchor-id="theory-of-factorial-anova-independent-design">12.2. Theory of factorial ANOVA (independent design)</h2>
<p>In previous chapter, we incorporated a second variable into the ANOVA framework when that variable is a continuous variable. Now, we’ll move on to situations where there is a second independent variable that has been systematically manipulated by assigning people to different conditions.</p>
<section id="factorial-designs" class="level3">
<h3 class="anchored" data-anchor-id="factorial-designs">12.2.1. Factorial designs</h3>
<p>When an experiment has two or more independent variables, it it known as a <strong>Factorial design.</strong></p>
<ul>
<li><p><strong>Independent factorial design</strong>: Several independent variables measured using different entities (between groups)</p></li>
<li><p><strong>Repeated-measures factorial design</strong>: Several independent variable measured, using the same entities in all conditions.</p></li>
<li><p><strong>Mixed design</strong>: Several independent variables in which some have been measured with different entities, whereas others used the same entities.</p></li>
</ul>
</section>
</section>
<section id="factorial-anova-as-regression" class="level2">
<h2 class="anchored" data-anchor-id="factorial-anova-as-regression">12.3. Factorial ANOVA as regression</h2>
<section id="an-example-with-two-independent-variables" class="level3">
<h3 class="anchored" data-anchor-id="an-example-with-two-independent-variables">12.3.1. An example with two independent variables</h3>
<p>How does gender and alcohol consumption affect the attractiveness?</p>
<p>attractiveness ~ gender (2 levels) + alcohol (3 levels)</p>
</section>
<section id="extending-the-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="extending-the-regression-model">12.3.2. Extending the regression model</h3>
<p>How do we extend the linear model to incorporate two independent variables?</p>
<p>We can set each variable using dummy coding, and add the interaction term like below:</p>
<p>attractiveness_i = ( <span class="math inline">\(b_0\)</span> + <span class="math inline">\(b_1\)</span>gender_i + <span class="math inline">\(b_2\)</span>alcohol_i + <span class="math inline">\(b_3\)</span>interaction_i ) + <span class="math inline">\(\epsilon_i\)</span></p>
<p>How do we code the interaction term? The interaction term represents the combined effect of <code>alcohol</code> and <code>gender</code>. To get any interaction term in regression, we simply multiply the variables involved. The interaction variable literally is the two dummy variables multiplied by each other.</p>
<ul>
<li><p><span class="math inline">\(b_0\)</span> in the model represents the mean of the group for which all variables are coded as 0. It’s the mean value of the base category.</p></li>
<li><p><span class="math inline">\(b_1\)</span> in the model represents the difference between men and women who had no alcohol. It’s the effect of <code>gender</code> for the base category of <code>alcohol</code> (In this case, no alcohol).</p></li>
<li><p><span class="math inline">\(b_2\)</span> in the model represents the difference between having no alcohol and 4 pints in <em>men</em>. It’s the effect of <code>alcohol</code> in the base category of <code>gender</code>. (In this case, men).</p></li>
<li><p><span class="math inline">\(b_3\)</span> in the model compares &lt;the difference between men and women in the no-alcohol condition&gt; to &lt;the difference between men and women in the 4 pints condition&gt;. It compares the effect of gender after no-alcohol to the effect of gender after 4 pints.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Self-test</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /Users/leedh/self_study/discoverstat</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>gogglesReg <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="fu">here</span>(<span class="st">"ch12"</span>, <span class="st">"GogglesRegression.dat"</span>), <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>gogglesRegModel <span class="ot">&lt;-</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(attractiveness <span class="sc">~</span> gender <span class="sc">+</span> alcohol <span class="sc">+</span> interaction, <span class="at">data =</span> gogglesReg)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gogglesRegModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = attractiveness ~ gender + alcohol + interaction, 
    data = gogglesReg)

Residuals:
    Min      1Q  Median      3Q     Max 
-16.875  -5.625  -0.625   5.156  19.375 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   66.875      3.055  21.890  &lt; 2e-16 ***
gender        -6.250      4.320  -1.447    0.159    
alcohol      -31.250      4.320  -7.233 7.13e-08 ***
interaction   28.125      6.110   4.603 8.20e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.641 on 28 degrees of freedom
Multiple R-squared:  0.6796,    Adjusted R-squared:  0.6452 
F-statistic: 19.79 on 3 and 28 DF,  p-value: 4.367e-07</code></pre>
</div>
</div>
</section>
</section>
<section id="two-way-anova-behind-the-scenes" class="level2">
<h2 class="anchored" data-anchor-id="two-way-anova-behind-the-scenes">12.4. Two-way ANOVA: behind the scenes</h2>
<p>Two-way ANOVA is conceptually very similar to one-way ANOVA. Basically, we still find the total sum of squared errors( <span class="math inline">\(SS_T\)</span> ) and break this variance down into variance that can be explained by the experiment( <span class="math inline">\(SS_M\)</span> ) and variance that cannot be explained( <span class="math inline">\(SS_R\)</span> ). In two-way ANOVA, we additionally break <span class="math inline">\(SS_M\)</span> into variance explained by the first independent variable<br>
( <span class="math inline">\(SS_A\)</span> ), variance explained by the second independent variable ( <span class="math inline">\(SS_B\)</span> ) and variance explained by the interaction of theses two variables ( <span class="math inline">\(SS_{AXB}\)</span> ).</p>
<section id="total-sums-of-squares-ss_t" class="level3">
<h3 class="anchored" data-anchor-id="total-sums-of-squares-ss_t">12.4.1. Total sums of squares <span class="math inline">\(SS_T\)</span></h3>
<p>We calculate how much variability there is between scores when we ignore the experimental condition from which they came. The degrees of freedom for <span class="math inline">\(SS_T\)</span> is N-1.</p>
</section>
<section id="the-model-sum-of-squares-ss_m" class="level3">
<h3 class="anchored" data-anchor-id="the-model-sum-of-squares-ss_m">12.4.2. The model sum of squares <span class="math inline">\(SS_M\)</span></h3>
<p>There are six groups in total, 2 for <code>gender</code>, 3 for <code>alcohol</code>. Therefore, the degrees of freedom for <span class="math inline">\(SS_M\)</span> will be the number of groups used, <em>k</em>, minus 1 (<em>df</em> = 5).</p>
<section id="the-main-effect-of-gender-ss_a" class="level4">
<h4 class="anchored" data-anchor-id="the-main-effect-of-gender-ss_a">12.4.2.1. The main effect of gender <span class="math inline">\(SS_A\)</span></h4>
<p>The main effect of <code>gender</code> compares the mean of all males against the mean of all females, regardless of which alcohol group they were in.</p>
<p>To work out the variance accounted for by the first independent variable <code>gender</code>, we ignore the amount of drink that has been drunk, and we just place all of the male scores into one group and all of the female scores into another.</p>
<p>The degrees of freedom for <span class="math inline">\(SS_A\)</span> will be the number of groups used, <em>k</em>, minus 1 (<em>df</em> = 1)</p>
</section>
<section id="the-main-effect-of-alcohol-ss_b" class="level4">
<h4 class="anchored" data-anchor-id="the-main-effect-of-alcohol-ss_b">12.4.2.2. The main effect of alcohol <span class="math inline">\(SS_B\)</span></h4>
<p>The main effect of <code>alcohol</code> compares the means of the no-alcohol, 2-pints and 4-pints groups, regardless of whether the scores come from men or women.</p>
<p>To work out the variance accounted for by the first independent variable <code>alcohol</code>, we ignore the gender of the participant, and we just place all of the scores after no drinks in one group, the scores after 2 pints in another group and the scores after 4 pints in a third group.</p>
<p>The degrees of freedom for <span class="math inline">\(SS_B\)</span> will be the number of groups used, <em>k</em>, minus 1 (<em>df</em> = 2)</p>
</section>
<section id="the-interaction-effect-ss_axb" class="level4">
<h4 class="anchored" data-anchor-id="the-interaction-effect-ss_axb">12.4.2.3. The interaction effect <span class="math inline">\(SS_{AXB}\)</span></h4>
<p>Given that we know <span class="math inline">\(SS_A\)</span> and <span class="math inline">\(SS_B\)</span>, we can calculate the interaction term using subtraction:</p>
<p><span class="math inline">\(SS_{AXB} = SS_M - SS_A - SS_B\)</span></p>
<p>The degrees of freedom can be calculated in the same way, but are also the product of the degrees of freedom for the main effects:</p>
<p><span class="math inline">\(df_{AXB} = df_M - df_A - df_B = 5 - 1 - 2 =2\)</span></p>
<p><span class="math inline">\(df_{AXB} = df_A X df_B = 1 X 2 =2\)</span></p>
</section>
</section>
<section id="the-residual-sum-of-squares-ss_r" class="level3">
<h3 class="anchored" data-anchor-id="the-residual-sum-of-squares-ss_r">12.4.3. The residual sum of squares <span class="math inline">\(SS_R\)</span></h3>
<p>The residual sum of squares represents individual differences in performance or the variance that can’t be explained by factors that were systematically manipulated.</p>
<p>The degrees of freedom for each group will be one less than the number of scores per group. Therefore, if we add the degrees of freedom for each group, we get the total degrees of freedom.</p>
</section>
<section id="the-f-ratios" class="level3">
<h3 class="anchored" data-anchor-id="the-f-ratios">12.4.4. The <em>F</em>-ratios</h3>
<p>Each effect in a two-way ANOVA has its own <em>F</em>-ratio. This is same as calculating the <em>F</em>-ratio in a one-way ANOVA.</p>
</section>
</section>
<section id="factorial-anova-using-r" class="level2">
<h2 class="anchored" data-anchor-id="factorial-anova-using-r">12.5. Factorial ANOVA using R</h2>
<section id="packages-for-factorial-anova-in-r" class="level3">
<h3 class="anchored" data-anchor-id="packages-for-factorial-anova-in-r">12.5.1. Packages for factorial ANOVA in R</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car); <span class="fu">library</span>(compute.es); <span class="fu">library</span>(effects); <span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp); <span class="fu">library</span>(pastecs); <span class="fu">library</span>(WRS2); <span class="fu">library</span>(reshape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: mvtnorm</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: survival</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: TH.data</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'TH.data'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:MASS':

    geyser</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="general-procedure-for-factorial-anova" class="level3">
<h3 class="anchored" data-anchor-id="general-procedure-for-factorial-anova">12.5.2. General procedure for factorial ANOVA</h3>
<ul>
<li><p>Enter data.</p></li>
<li><p>Explore data by graphing the data and computing descriptive statistics.</p></li>
<li><p>Construct or choose contrasts. The contrasts must be orthogonal.</p></li>
<li><p>Compute the ANOVA.</p></li>
<li><p>Compute contrasts or <em>post hoc</em> tests.</p></li>
</ul>
</section>
<section id="factorial-anova-using-r-commander" class="level3">
<h3 class="anchored" data-anchor-id="factorial-anova-using-r-commander">12.5.3. Factorial ANOVA using R Commander</h3>
</section>
<section id="entering-the-data" class="level3">
<h3 class="anchored" data-anchor-id="entering-the-data">12.5.4. Entering the data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>gogglesData2 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"ch12"</span>, <span class="st">"goggles.csv"</span>), <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gogglesData2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  gender alcohol attractiveness
1 Female    None             65
2 Female    None             70
3 Female    None             60
4 Female    None             60
5 Female    None             60
6 Female    None             55</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>gogglesData2<span class="sc">$</span>alcohol <span class="ot">&lt;-</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(gogglesData2<span class="sc">$</span>alcohol, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"None"</span>, <span class="st">"2 Pints"</span>, <span class="st">"4 Pints"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can create coding variables by using the <code>gl()</code> function.</p>
<p><code>factor &lt;-gl(number of levels, cases in each level, total cases, labels = c("label1", "label2", ...)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">2</span>, <span class="dv">24</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>alcohol <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">3</span>, <span class="dv">8</span>, <span class="dv">48</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"None"</span>, <span class="st">"2 Pints"</span>, <span class="st">"4 Pints"</span>))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>attractiveness <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">65</span>,<span class="dv">70</span>,<span class="dv">60</span>,<span class="dv">60</span>,<span class="dv">60</span>,<span class="dv">55</span>,<span class="dv">60</span>,<span class="dv">55</span>,<span class="dv">70</span>,<span class="dv">65</span>,<span class="dv">60</span>,<span class="dv">70</span>,<span class="dv">65</span>,<span class="dv">60</span>,<span class="dv">60</span>,<span class="dv">50</span>,<span class="dv">55</span>,<span class="dv">65</span>,<span class="dv">70</span>,<span class="dv">55</span>,<span class="dv">55</span>,<span class="dv">60</span>,<span class="dv">50</span>,<span class="dv">50</span>,<span class="dv">50</span>,<span class="dv">55</span>,<span class="dv">80</span>,<span class="dv">65</span>,<span class="dv">70</span>,<span class="dv">75</span>,<span class="dv">75</span>,<span class="dv">65</span>,<span class="dv">45</span>,<span class="dv">60</span>,<span class="dv">85</span>,<span class="dv">65</span>,<span class="dv">70</span>,<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">60</span>,<span class="dv">30</span>,<span class="dv">30</span>,<span class="dv">30</span>,<span class="dv">55</span>,<span class="dv">35</span>,<span class="dv">20</span>,<span class="dv">45</span>,<span class="dv">40</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>gogglesData <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(gender, alcohol, attractiveness)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gogglesData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  gender alcohol attractiveness
1 Female    None             65
2 Female    None             70
3 Female    None             60
4 Female    None             60
5 Female    None             60
6 Female    None             55</code></pre>
</div>
</div>
</section>
<section id="exploring-the-data" class="level3">
<h3 class="anchored" data-anchor-id="exploring-the-data">12.5.5. Exploring the data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>line <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gogglesData, <span class="fu">aes</span>(alcohol, attractiveness, <span class="at">colour =</span> gender))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>line <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="fu">aes</span>(<span class="at">group=</span> gender)) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Alcohol Consumption"</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Attractiveness of Date (%)"</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Gender"</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `fun.y` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.
ℹ Please use the `fun` argument instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="chapter_12_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>boxplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gogglesData, <span class="fu">aes</span>(alcohol, attractiveness))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>boxplot <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Alcohol Consumption"</span>, <span class="at">y =</span> <span class="st">"Mean Attractiveness of Date (%)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapter_12_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The resulting line graph is what is known as an interaction graph.</p>
<p>From the box plot, the median score for females doesn’t change much across the doses of alcohol, and also the spread of their scores is relatively narrow. However, for males, the spread of scores is wider than for females, and the median attractiveness seems to fall dramatically after 4 pints.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">by</span>(gogglesData<span class="sc">$</span>attractiveness, gogglesData<span class="sc">$</span>gender, stat.desc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>gogglesData$gender: Female
     nbr.val     nbr.null       nbr.na          min          max        range 
  24.0000000    0.0000000    0.0000000   50.0000000   70.0000000   20.0000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
1445.0000000   60.0000000   60.2083333    1.2937687    2.6763646   40.1721014 
     std.dev     coef.var 
   6.3381465    0.1052703 
------------------------------------------------------------ 
gogglesData$gender: Male
     nbr.val     nbr.null       nbr.na          min          max        range 
  24.0000000    0.0000000    0.0000000   20.0000000   85.0000000   65.0000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
1355.0000000   60.0000000   56.4583333    3.7768263    7.8129606  342.3460145 
     std.dev     coef.var 
  18.5025948    0.3277212 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">by</span>(gogglesData<span class="sc">$</span>attractiveness, gogglesData<span class="sc">$</span>alcohol, stat.desc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>gogglesData$alcohol: None
     nbr.val     nbr.null       nbr.na          min          max        range 
   16.000000     0.000000     0.000000    50.000000    80.000000    30.000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
 1020.000000    62.500000    63.750000     2.116404     4.511009    71.666667 
     std.dev     coef.var 
    8.465617     0.132794 
------------------------------------------------------------ 
gogglesData$alcohol: 2 Pints
     nbr.val     nbr.null       nbr.na          min          max        range 
  16.0000000    0.0000000    0.0000000   45.0000000   85.0000000   40.0000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
1035.0000000   65.0000000   64.6875000    2.4777657    5.2812326   98.2291667 
     std.dev     coef.var 
   9.9110628    0.1532145 
------------------------------------------------------------ 
gogglesData$alcohol: 4 Pints
     nbr.val     nbr.null       nbr.na          min          max        range 
  16.0000000    0.0000000    0.0000000   20.0000000   70.0000000   50.0000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
 745.0000000   50.0000000   46.5625000    3.5858155    7.6429849  205.7291667 
     std.dev     coef.var 
  14.3432621    0.3080432 </code></pre>
</div>
</div>
<p>The resulting output shows the effects of alcohol and gender on the attractiveness of the dates selected.</p>
<p>However, we are also interested in how these variable interact. To do this, we need to use the <code>list()</code> function to create a list of variables that we can then feed into the <code>by()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">by</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  gogglesData<span class="sc">$</span>attractiveness,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(gogglesData<span class="sc">$</span>alcohol, gogglesData<span class="sc">$</span>gender),</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  stat.desc</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>: None
: Female
     nbr.val     nbr.null       nbr.na          min          max        range 
  8.00000000   0.00000000   0.00000000  55.00000000  70.00000000  15.00000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
485.00000000  60.00000000  60.62500000   1.75191222   4.14261412  24.55357143 
     std.dev     coef.var 
  4.95515604   0.08173453 
------------------------------------------------------------ 
: 2 Pints
: Female
     nbr.val     nbr.null       nbr.na          min          max        range 
   8.0000000    0.0000000    0.0000000   50.0000000   70.0000000   20.0000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
 500.0000000   62.5000000   62.5000000    2.3145502    5.4730417   42.8571429 
     std.dev     coef.var 
   6.5465367    0.1047446 
------------------------------------------------------------ 
: 4 Pints
: Female
     nbr.val     nbr.null       nbr.na          min          max        range 
   8.0000000    0.0000000    0.0000000   50.0000000   70.0000000   20.0000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
 460.0000000   55.0000000   57.5000000    2.5000000    5.9115606   50.0000000 
     std.dev     coef.var 
   7.0710678    0.1229751 
------------------------------------------------------------ 
: None
: Male
     nbr.val     nbr.null       nbr.na          min          max        range 
   8.0000000    0.0000000    0.0000000   50.0000000   80.0000000   30.0000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
 535.0000000   67.5000000   66.8750000    3.6519931    8.6355914  106.6964286 
     std.dev     coef.var 
  10.3293963    0.1544583 
------------------------------------------------------------ 
: 2 Pints
: Male
     nbr.val     nbr.null       nbr.na          min          max        range 
   8.0000000    0.0000000    0.0000000   45.0000000   85.0000000   40.0000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
 535.0000000   67.5000000   66.8750000    4.4257263   10.4651798  156.6964286 
     std.dev     coef.var 
  12.5178444    0.1871827 
------------------------------------------------------------ 
: 4 Pints
: Male
     nbr.val     nbr.null       nbr.na          min          max        range 
   8.0000000    0.0000000    0.0000000   20.0000000   55.0000000   35.0000000 
         sum       median         mean      SE.mean CI.mean.0.95          var 
 285.0000000   32.5000000   35.6250000    3.8309711    9.0588071  117.4107143 
     std.dev     coef.var 
  10.8356225    0.3041578 </code></pre>
</div>
</div>
<p>We are primarily interested in the interaction of <code>gender</code> and <code>alcohol</code>, so we would ideally like to know whether the variances differ across all six groups, not just the two gender groups and three alcohol groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Not our interest</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(gogglesData<span class="sc">$</span>attractiveness, gogglesData<span class="sc">$</span>gender, <span class="at">center =</span> median)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value   Pr(&gt;F)    
group  1  19.979 5.08e-05 ***
      46                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(gogglesData<span class="sc">$</span>attractiveness, gogglesData<span class="sc">$</span>alcohol, <span class="at">center =</span> median)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  2  2.3238 0.1095
      45               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Our interest</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  gogglesData<span class="sc">$</span>attractiveness,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">interaction</span>(gogglesData<span class="sc">$</span>alcohol, gogglesData<span class="sc">$</span>gender),</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">center =</span> median</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  5  1.4252 0.2351
      42               </code></pre>
</div>
</div>
<p>The results of Levene’s test show that the assumption has met.</p>
</section>
<section id="choosing-contrasts" class="level3">
<h3 class="anchored" data-anchor-id="choosing-contrasts">12.5.6. Choosing contrasts</h3>
<p>We have to define contrasts for <em>all</em> of the independent variables. Our first contrast should compare the no-alcohol group to the remaining categories. Our second contrast is comparing the two alcohol groups.</p>
<table class="table">
<caption>Orthogonal contrasts for the ‘alcohol’ variable</caption>
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: center;">Contrast 1</th>
<th style="text-align: center;">Contrast 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No Alcohol</td>
<td style="text-align: center;">-2</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td>2 Pints</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">-1</td>
</tr>
<tr class="odd">
<td>4 Pints</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
<p>In this case, we’ll get not only a contrast comparing no alcohol to the combined effect of 2 and 4 pints, <strong>but also one that tests whether this effect is different in men and women.</strong> Similarly, contrast 2 tests whether the 2- and 4- pints groups differ, but we will also get a parameter estimate that tests <strong>whether difference between the 2- and 4- pints groups is affected by the gender of the participant</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(gogglesData<span class="sc">$</span>alcohol) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(gogglesData<span class="sc">$</span>gender) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>gogglesData<span class="sc">$</span>alcohol</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] None    None    None    None    None    None    None    None    2 Pints
[10] 2 Pints 2 Pints 2 Pints 2 Pints 2 Pints 2 Pints 2 Pints 4 Pints 4 Pints
[19] 4 Pints 4 Pints 4 Pints 4 Pints 4 Pints 4 Pints None    None    None   
[28] None    None    None    None    None    2 Pints 2 Pints 2 Pints 2 Pints
[37] 2 Pints 2 Pints 2 Pints 2 Pints 4 Pints 4 Pints 4 Pints 4 Pints 4 Pints
[46] 4 Pints 4 Pints 4 Pints
attr(,"contrasts")
        [,1] [,2]
None      -2    0
2 Pints    1   -1
4 Pints    1    1
Levels: None 2 Pints 4 Pints</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>gogglesData<span class="sc">$</span>gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Female Female Female Female Female Female Female Female Female Female
[11] Female Female Female Female Female Female Female Female Female Female
[21] Female Female Female Female Male   Male   Male   Male   Male   Male  
[31] Male   Male   Male   Male   Male   Male   Male   Male   Male   Male  
[41] Male   Male   Male   Male   Male   Male   Male   Male  
attr(,"contrasts")
       [,1]
Female   -1
Male      1
Levels: Female Male</code></pre>
</div>
</div>
</section>
<section id="fitting-a-factorial-anova-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-factorial-anova-model">12.5.7. Fitting a factorial ANOVA model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>gogglesModel <span class="ot">&lt;-</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aov</span>(attractiveness <span class="sc">~</span> gender <span class="sc">+</span> alcohol <span class="sc">+</span> gender<span class="sc">:</span>alcohol, <span class="at">data =</span> gogglesData)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(gogglesModel, <span class="at">type =</span> <span class="st">"III"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: attractiveness
               Sum Sq Df   F value    Pr(&gt;F)    
(Intercept)    163333  1 1967.0251 &lt; 2.2e-16 ***
gender            169  1    2.0323    0.1614    
alcohol          3332  2   20.0654 7.649e-07 ***
gender:alcohol   1978  2   11.9113 7.987e-05 ***
Residuals        3488 42                        
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="interpreting-factorial-anova" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-factorial-anova">12.5.8. Interpreting factorial ANOVA</h3>
<p>There was a significant main effect of <code>alcohol</code>. This means that overall, when we ignore whether the participant was male or female, the amount of alcohol influenced their mate selection.</p>
<p>The main effect of <code>gender</code> was not significant, which means that overall, when we ignore how much alcohol had been drunk, the gender of the participant did not influence the attractiveness of the partner that the participant selected.</p>
<p>The interaction between the effect of <code>gender</code> and the effect of <code>alcohol</code> was significant. This means that the effect of alcohol on mate selection was different for male participants than it was for females. <strong>In the presence of this significant interaction it makes no sense to interpret the main effects</strong>, because the interaction effect tells us that this is true only in males.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>bar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gogglesData, <span class="fu">aes</span>(gender, attractiveness))</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>bar <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"bar"</span>, <span class="at">fill =</span> <span class="st">"White"</span>, <span class="at">colour =</span> <span class="st">"Black"</span>) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal, <span class="at">geom =</span> <span class="st">"pointrange"</span>) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Gender"</span>, <span class="at">y =</span> <span class="st">"Mean Attractiveness of Date (%)"</span>) <span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">80</span>, <span class="at">by =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapter_12_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>bar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gogglesData, <span class="fu">aes</span>(alcohol, attractiveness))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>bar <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"bar"</span>, <span class="at">fill =</span> <span class="st">"White"</span>, <span class="at">colour =</span> <span class="st">"Black"</span>) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal, <span class="at">geom =</span> <span class="st">"pointrange"</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Alcohol Consumption"</span>, <span class="at">y =</span> <span class="st">"Mean Attractiveness of Date (%)"</span>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">80</span>, <span class="at">by =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapter_12_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>line <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(gogglesData, <span class="fu">aes</span>(alcohol, attractiveness, <span class="at">colour =</span> gender))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>line <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="fu">aes</span>(<span class="at">group=</span> gender)) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Alcohol Consumption"</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Attractiveness of Date (%)"</span>,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Gender"</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapter_12_files/figure-html/unnamed-chunk-11-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="interpreting-contrasts" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-contrasts">12.5.9. Interpreting contrasts</h3>
<p>To see the output for the contrasts that we specified, we execute:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.lm</span>(gogglesModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
aov(formula = attractiveness ~ gender + alcohol + gender:alcohol, 
    data = gogglesData)

Residuals:
    Min      1Q  Median      3Q     Max 
-21.875  -5.625  -0.625   5.156  19.375 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        58.333      1.315  44.351  &lt; 2e-16 ***
gender1            -1.875      1.315  -1.426 0.161382    
alcohol1           -2.708      0.930  -2.912 0.005727 ** 
alcohol2           -9.062      1.611  -5.626 1.37e-06 ***
gender1:alcohol1   -2.500      0.930  -2.688 0.010258 *  
gender1:alcohol2   -6.562      1.611  -4.074 0.000201 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.112 on 42 degrees of freedom
Multiple R-squared:  0.6111,    Adjusted R-squared:  0.5648 
F-statistic:  13.2 on 5 and 42 DF,  p-value: 9.609e-08</code></pre>
</div>
</div>
<ul>
<li><p><code>gender1</code>: Contrast for the main effect of gender. The <em>t</em>- and <em>F</em>- statistics are directly related by <span class="math inline">\(F = t^2\)</span>. Our <em>t</em>-value for this contrast is -1.426, and the value of <em>F</em> for the effect of gender is <span class="math inline">\((-1.426)^2 = 2.03\)</span>.</p></li>
<li><p><code>alcohol1</code>: Tests whether the no-alcohol group(mean 63.75) and the two alcohol groups(mean (64.69+46.56)/2 = 55.625) differed.<br>
Mean difference: 55.63-63.75 = -8.125, Estimate: -8.125/3 = -2.708 (significant)<br>
Estimate for the difference is the difference divided by the number of groups involved in the contrast.</p></li>
<li><p><code>alcohol2</code>: Tests whether the 2-pints group (64.69) and 4-pints group (46.56) differed.<br>
Mean difference: 46.56-64.69 = -18.13, Estimate: -18.13/2 = 9.06 (significant)</p></li>
<li><p><code>gender1:alcohol1</code>: Tests whether the effect of <code>alcohol1</code> described above is different in men and women.<br>
“Is the effect of alcohol compared to no alcohol on the attractiveness of dates comparable in men and women?” -&gt; NO<br>
Which alcohol vs.&nbsp;no alcohol had an effect on date attractiveness is different in men and women. In terms of graph, it tests whether the lines for males and females have different slopes.</p></li>
<li><p><code>gender1:alcohol2</code>: Tests whether the effect of <code>alcohol2</code> described above is different in men and women.<br>
“Is the effect of 2 pints compared to 4 pints on the attractiveness of dates comparable in men and women?” -&gt; NO<br>
Comparing the mean difference of 2- and 4- pints in women (57.50-62.50 = -5) and that in men (35.625-66.875).</p></li>
</ul>
</section>
<section id="simple-effects-analysis" class="level3">
<h3 class="anchored" data-anchor-id="simple-effects-analysis">12.5.10. Simple effects analysis</h3>
<p><strong>Simple effects analysis</strong> looks at the effect of one independent variable at individual levels of the other independent variable.</p>
<table class="table">
<colgroup>
<col style="width: 37%">
<col style="width: 17%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0 M</td>
<td style="text-align: center;">0 F</td>
<td style="text-align: center;">2 F</td>
<td style="text-align: center;">2 M</td>
<td style="text-align: center;">4 F</td>
<td style="text-align: center;">4 M</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Contrast 1</td>
<td style="text-align: center;">-2</td>
<td style="text-align: center;">-2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Contrast 2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Simple effect of gender</td>
<td style="text-align: center;">Contrast 3</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Simple effect of gender</td>
<td style="text-align: center;">Contrast 4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">Simple effect of gender</td>
<td style="text-align: center;">Contrast 5</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">-1</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
<p>Simple effects are not easy to do in <strong>R</strong> because we need a new variable that simple codes the six groups that result from combining all levels of <code>alcohol</code> and <code>gender</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>gogglesData<span class="sc">$</span>simple <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">6</span>, <span class="dv">8</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>gogglesData<span class="sc">$</span>simple <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  gogglesData<span class="sc">$</span>simple,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>),</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"F_None"</span>,<span class="st">"F_2pints"</span>, <span class="st">"F_4pints"</span>, <span class="st">"M_None"</span>, <span class="st">"M_2pints"</span>, <span class="st">"M_4pints"</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Making contrasts</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>alcEffect1<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>alcEffect2<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>gender_none<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>gender_twoPint<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>gender_fourPint<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge these variables into an object</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>simpleEff <span class="ot">&lt;-</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(alcEffect1, alcEffect2, gender_none, gender_twoPint, gender_fourPint)</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(gogglesData<span class="sc">$</span>simple) <span class="ot">&lt;-</span> simpleEff</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>simpleEffectModel <span class="ot">&lt;-</span> <span class="fu">aov</span>(attractiveness <span class="sc">~</span> simple, <span class="at">data =</span> gogglesData)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.lm</span>(simpleEffectModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
aov(formula = attractiveness ~ simple, data = gogglesData)

Residuals:
    Min      1Q  Median      3Q     Max 
-21.875  -5.625  -0.625   5.156  19.375 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             58.333      1.315  44.351  &lt; 2e-16 ***
simplealcEffect1        -2.708      0.930  -2.912  0.00573 ** 
simplealcEffect2        -9.062      1.611  -5.626 1.37e-06 ***
simplegender_none        3.125      2.278   1.372  0.17742    
simplegender_twoPint     2.188      2.278   0.960  0.34243    
simplegender_fourPint  -10.938      2.278  -4.801 2.02e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.112 on 42 degrees of freedom
Multiple R-squared:  0.6111,    Adjusted R-squared:  0.5648 
F-statistic:  13.2 on 5 and 42 DF,  p-value: 9.609e-08</code></pre>
</div>
</div>
<p>The result shows that there was no significant difference between men and women when they drank no alcohol or when they drank 2 pints, but there was a very significant difference when 4 pints were consumed.</p>
</section>
<section id="post-hoc-analysis" class="level3">
<h3 class="anchored" data-anchor-id="post-hoc-analysis">12.5.11. <em>Post hoc</em> analysis</h3>
<p>The author covers <em>post hoc</em> tests here for illustrative purposes. The author would focus on the interaction effect and not perform <em>post hoc</em> tests on <code>alcohol</code> if it were real research.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  gogglesData<span class="sc">$</span>attractiveness,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  gogglesData<span class="sc">$</span>alcohol,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  gogglesData$attractiveness and gogglesData$alcohol 

        None    2 Pints
2 Pints 1.00000 -      
4 Pints 0.00024 0.00011

P value adjustment method: bonferroni </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>postHocs <span class="ot">&lt;-</span> <span class="fu">glht</span>(gogglesModel, <span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="at">alcohol =</span> <span class="st">"Tukey"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in mcp2matrix(model, linfct = linfct): covariate interactions found --
default contrast might be inappropriate</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(postHocs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: Tukey Contrasts


Fit: aov(formula = attractiveness ~ gender + alcohol + gender:alcohol, 
    data = gogglesData)

Linear Hypotheses:
                       Estimate Std. Error t value Pr(&gt;|t|)    
2 Pints - None == 0      0.9375     3.2217   0.291    0.954    
4 Pints - None == 0    -17.1875     3.2217  -5.335   &lt;1e-04 ***
4 Pints - 2 Pints == 0 -18.1250     3.2217  -5.626   &lt;1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(postHocs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Confidence Intervals

Multiple Comparisons of Means: Tukey Contrasts


Fit: aov(formula = attractiveness ~ gender + alcohol + gender:alcohol, 
    data = gogglesData)

Quantile = 2.4296
95% family-wise confidence level
 

Linear Hypotheses:
                       Estimate lwr      upr     
2 Pints - None == 0      0.9375  -6.8899   8.7649
4 Pints - None == 0    -17.1875 -25.0149  -9.3601
4 Pints - 2 Pints == 0 -18.1250 -25.9524 -10.2976</code></pre>
</div>
</div>
<p>Both tests show the same pattern of results: when participants had drunk no alcohol or 2 pints of alcohol, they selected equally attractive mates. However, after 4 pints had been consumed, participants selected significantly less attractive mates than after both 2 pints and no alcohol.</p>
</section>
<section id="overall-conclusions" class="level3">
<h3 class="anchored" data-anchor-id="overall-conclusions">12.5.12. Overall conclusions</h3>
<ul>
<li><p>Alcohol has an effect on the attractiveness of selected mates.</p></li>
<li><p>Men are significantly more likely to pick less attractive mates when drunk.</p></li>
</ul>
</section>
<section id="plots-in-factorial-anova" class="level3">
<h3 class="anchored" data-anchor-id="plots-in-factorial-anova">12.5.13. Plots in factorial ANOVA</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gogglesModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="chapter_12_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="chapter_12_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="chapter_12_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="chapter_12_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="interpreting-interaction-graphs" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-interaction-graphs">12.6. Interpreting interaction graphs</h2>
<ul>
<li><p>Non-parallel lines on an interaction graph <strong>imply</strong> significant interactions.</p></li>
<li><p>If the lines on an interaction graph cross then obviously they are not parallel and this can give away a possible significant interaction.</p></li>
</ul>
</section>
<section id="robust-factorial-anova" class="level2">
<h2 class="anchored" data-anchor-id="robust-factorial-anova">12.7. Robust factorial ANOVA</h2>
<ul>
<li><p><code>t2way()</code> performs a two-way independent ANOVA on trimmed means.</p></li>
<li><p><code>mcp2atm()</code> performs <em>post hoc</em> tests for a two-way independent design based on trimmed means.</p></li>
<li><p><code>pbad2way()</code> performs a two-way independent ANOVA using M-measures of location (e.g., median) and a bootstrap.</p></li>
<li><p><code>mcp2a()</code> performs <em>post hoc</em> tests for the above function.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>gogglesData2<span class="sc">$</span>row<span class="ot">&lt;-</span><span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>, <span class="dv">6</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>gogglesMelt <span class="ot">&lt;-</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">melt</span>(</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>    gogglesData2,</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">id =</span> <span class="fu">c</span>(<span class="st">"row"</span>, <span class="st">"gender"</span>, <span class="st">"alcohol"</span>),</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">measured =</span> <span class="fu">c</span>( <span class="st">"attractiveness"</span>)</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can cast the data by using a formula in the form: <em>variables specifying the rows ~ variables specifying the columns</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>gogglesWide <span class="ot">&lt;-</span> <span class="fu">cast</span>(gogglesMelt,  row <span class="sc">~</span> gender <span class="sc">+</span> alcohol)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gogglesWide)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  row Female_None Female_2 Pints Female_4 Pints Male_None Male_2 Pints
1   1          65             70             55        50           45
2   2          70             65             65        55           60
3   3          60             60             70        80           85
4   4          60             70             55        65           65
5   5          60             65             55        70           70
6   6          55             60             60        75           70
  Male_4 Pints
1           30
2           30
3           30
4           55
5           35
6           20</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove 'row'</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>gogglesWide<span class="sc">$</span>row <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gogglesWide)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Female_None Female_2 Pints Female_4 Pints Male_None Male_2 Pints Male_4 Pints
1          65             70             55        50           45           30
2          70             65             65        55           60           30
3          60             60             70        80           85           30
4          60             70             55        65           65           55
5          60             65             55        70           70           35
6          55             60             60        75           70           20</code></pre>
</div>
</div>
<p>It’s important to note the order of the columns because this affects how we specify the robust analysis. In this case, the hierarchy of the independent variables is <code>gender</code> followed by <code>alcohol</code>.</p>
<p>The function <code>t2way()</code> takes the general form:</p>
<p><code>t2way(levels of factor A, levels of factor B, data, tr = .2, alpha = .05)</code> (Incorrect info)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t2way</span>(attractiveness <span class="sc">~</span> gender<span class="sc">*</span>alcohol, <span class="at">data =</span> gogglesWide)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
t2way(formula = attractiveness ~ gender * alcohol, data = gogglesWide)

                 value p.value
gender          1.6667   0.209
alcohol        48.2845   0.001
gender:alcohol 26.2572   0.001</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbad2way</span>(attractiveness <span class="sc">~</span> gender<span class="sc">*</span>alcohol, <span class="at">data =</span> gogglesData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
pbad2way(formula = attractiveness ~ gender * alcohol, data = gogglesData)

               p.value
gender          0.1569
alcohol         0.0000
gender:alcohol  0.0000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcp2atm</span>(attractiveness <span class="sc">~</span> gender<span class="sc">*</span>alcohol, <span class="at">data =</span> gogglesData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
mcp2atm(formula = attractiveness ~ gender * alcohol, data = gogglesData)

                    psihat  ci.lower  ci.upper p-value
gender1           10.00000  -6.00223  26.00223 0.20922
alcohol1          -3.33333 -20.49551  13.82885 0.61070
alcohol2          35.83333  19.32755  52.33911 0.00003
alcohol3          39.16667  22.46796  55.86537 0.00001
gender1:alcohol1  -3.33333 -20.49551  13.82885 0.61070
gender1:alcohol2 -29.16667 -45.67245 -12.66089 0.00025
gender1:alcohol3 -25.83333 -42.53204  -9.13463 0.00080</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcp2a</span>(attractiveness <span class="sc">~</span> gender<span class="sc">*</span>alcohol, <span class="at">data =</span> gogglesData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
mcp2a(formula = attractiveness ~ gender * alcohol, data = gogglesData)

                    psihat  ci.lower  ci.upper p-value
gender1           14.46429  -8.09524  27.70833 0.14524
alcohol1          -5.00000 -17.87500  12.70833 0.40234
alcohol2          35.80357  19.37500  50.04167 0.00000
alcohol3          40.80357  22.50000  53.75000 0.00000
gender1:alcohol1  -5.00000 -18.80357  13.33333 0.28881
gender1:alcohol2 -32.23214 -45.53571 -12.00000 0.00000
gender1:alcohol3 -27.23214 -43.57143  -9.10714 0.00167</code></pre>
</div>
</div>
</section>
<section id="calculating-effect-sizes" class="level2">
<h2 class="anchored" data-anchor-id="calculating-effect-sizes">12.8. Calculating effect sizes</h2>
<p>We need to first compute a variance component for each of the effects (the two main effects and the interaction term) and the error, and then use these to calculate effect sizes for each:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>omega_factorial <span class="ot">&lt;-</span> <span class="cf">function</span>(n,a,b, SSa, SSb, SSab, SSr)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>    MSa <span class="ot">&lt;-</span> SSa <span class="sc">/</span> (a<span class="dv">-1</span>)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>    MSb <span class="ot">&lt;-</span> SSb <span class="sc">/</span> (b<span class="dv">-1</span>)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>    MSab <span class="ot">&lt;-</span> SSab <span class="sc">/</span> ((a<span class="dv">-1</span>)<span class="sc">*</span>(b<span class="dv">-1</span>))</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>    MSr <span class="ot">&lt;-</span> SSr <span class="sc">/</span> (a<span class="sc">*</span>b<span class="sc">*</span>(n<span class="dv">-1</span>))</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>    varA <span class="ot">&lt;-</span> ((a<span class="dv">-1</span>)<span class="sc">*</span>(MSa<span class="sc">-</span>MSr)) <span class="sc">/</span> (n<span class="sc">*</span>a<span class="sc">*</span>b)</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>    varB <span class="ot">&lt;-</span> ((b<span class="dv">-1</span>)<span class="sc">*</span>(MSb<span class="sc">-</span>MSr)) <span class="sc">/</span> (n<span class="sc">*</span>a<span class="sc">*</span>b)</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>    varAB <span class="ot">&lt;-</span> ((a<span class="dv">-1</span>)<span class="sc">*</span>(b<span class="dv">-1</span>)<span class="sc">*</span>(MSab<span class="sc">-</span>MSr)) <span class="sc">/</span> (n<span class="sc">*</span>a<span class="sc">*</span>b)</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>    varTotal <span class="ot">&lt;-</span> varA <span class="sc">+</span> varB <span class="sc">+</span> varAB <span class="sc">+</span> MSr</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Omega-Squared A: "</span>, varA<span class="sc">/</span>varTotal))</span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Omega-Squared B: "</span>, varB<span class="sc">/</span>varTotal))</span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Omega-Squared AB: "</span>, varAB<span class="sc">/</span>varTotal))</span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb71-16"><a href="#cb71-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb71-17"><a href="#cb71-17" aria-hidden="true" tabindex="-1"></a><span class="fu">omega_factorial</span>(<span class="dv">8</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">169</span>, <span class="dv">3332</span>, <span class="dv">1978</span>, <span class="dv">3488</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Omega-Squared A:  0.00949745068429001"
[1] "Omega-Squared B:  0.34982188991376"
[1] "Omega-Squared AB:  0.200209417472152"</code></pre>
</div>
</div>
<p>We might compute effect sizes for the effect of gender at different levels of alcohol.</p>
<p>To compare men and women who drank no alcohol, we would enter the mean of the men who drank no alcohol (66.875), the mean of women who drank no alcohol (60.625), the corresponding SDs (10.329, 4.955), and the sample sizes (both 8):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mes</span>(<span class="fl">66.875</span>, <span class="fl">60.625</span>, <span class="fl">10.3293963</span>, <span class="fl">4.95515604</span>, <span class="dv">8</span>, <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean Differences ES: 
 
 d [ 95 %CI] = 0.77 [ -0.24 , 1.79 ] 
  var(d) = 0.27 
  p-value(d) = 0.16 
  U3(d) = 77.98 % 
  CLES(d) = 70.73 % 
  Cliff's Delta = 0.41 
 
 g [ 95 %CI] = 0.73 [ -0.23 , 1.69 ] 
  var(g) = 0.24 
  p-value(g) = 0.16 
  U3(g) = 76.71 % 
  CLES(g) = 69.7 % 
 
 Correlation ES: 
 
 r [ 95 %CI] = 0.38 [ -0.14 , 0.74 ] 
  var(r) = 0.04 
  p-value(r) = 0.17 
 
 z [ 95 %CI] = 0.4 [ -0.14 , 0.95 ] 
  var(z) = 0.08 
  p-value(z) = 0.17 
 
 Odds Ratio ES: 
 
 OR [ 95 %CI] = 4.05 [ 0.64 , 25.58 ] 
  p-value(OR) = 0.16 
 
 Log OR [ 95 %CI] = 1.4 [ -0.44 , 3.24 ] 
  var(lOR) = 0.88 
  p-value(Log OR) = 0.16 
 
 Other: 
 
 NNT = 3.68 
 Total N = 16</code></pre>
</div>
</div>
<p>Similarly, we can get effect sizes for the difference between men and women who drank 2 pints and 4 pints:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2 pints</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mes</span>(<span class="fl">66.875</span>, <span class="fl">62.5</span>, <span class="fl">12.5178444</span>, <span class="fl">6.5465367</span>, <span class="dv">8</span>, <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean Differences ES: 
 
 d [ 95 %CI] = 0.44 [ -0.55 , 1.43 ] 
  var(d) = 0.26 
  p-value(d) = 0.4 
  U3(d) = 66.93 % 
  CLES(d) = 62.16 % 
  Cliff's Delta = 0.24 
 
 g [ 95 %CI] = 0.41 [ -0.52 , 1.35 ] 
  var(g) = 0.23 
  p-value(g) = 0.4 
  U3(g) = 66.06 % 
  CLES(g) = 61.52 % 
 
 Correlation ES: 
 
 r [ 95 %CI] = 0.23 [ -0.3 , 0.65 ] 
  var(r) = 0.06 
  p-value(r) = 0.42 
 
 z [ 95 %CI] = 0.23 [ -0.31 , 0.78 ] 
  var(z) = 0.08 
  p-value(z) = 0.42 
 
 Odds Ratio ES: 
 
 OR [ 95 %CI] = 2.21 [ 0.37 , 13.37 ] 
  p-value(OR) = 0.4 
 
 Log OR [ 95 %CI] = 0.79 [ -1 , 2.59 ] 
  var(lOR) = 0.84 
  p-value(Log OR) = 0.4 
 
 Other: 
 
 NNT = 6.98 
 Total N = 16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 4 pints</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mes</span>(<span class="fl">35.625</span>, <span class="fl">57.5</span>, <span class="fl">10.8356225</span>, <span class="fl">7.0710678</span>, <span class="dv">8</span>, <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean Differences ES: 
 
 d [ 95 %CI] = -2.39 [ -3.67 , -1.11 ] 
  var(d) = 0.43 
  p-value(d) = 0 
  U3(d) = 0.84 % 
  CLES(d) = 4.55 % 
  Cliff's Delta = -0.91 
 
 g [ 95 %CI] = -2.26 [ -3.47 , -1.05 ] 
  var(g) = 0.38 
  p-value(g) = 0 
  U3(g) = 1.19 % 
  CLES(g) = 5.5 % 
 
 Correlation ES: 
 
 r [ 95 %CI] = -0.79 [ -0.92 , -0.48 ] 
  var(r) = 0.01 
  p-value(r) = 0 
 
 z [ 95 %CI] = -1.06 [ -1.61 , -0.52 ] 
  var(z) = 0.08 
  p-value(z) = 0 
 
 Odds Ratio ES: 
 
 OR [ 95 %CI] = 0.01 [ 0 , 0.13 ] 
  p-value(OR) = 0 
 
 Log OR [ 95 %CI] = -4.34 [ -6.66 , -2.01 ] 
  var(lOR) = 1.41 
  p-value(Log OR) = 0 
 
 Other: 
 
 NNT = -5.02 
 Total N = 16</code></pre>
</div>
</div>
<p>The difference in attractiveness scores between males and females who drank no alcohol is a medium effect, d = 0.77, r = .36;<br>
The difference between males and females who drank 2 pints is a fairly small effect, d = 0.44, r = .21;<br>
The difference between males and females who drank 4 pints is a very large effect, d = -2.39, r = -.77.</p>
</section>
<section id="reporting-the-results-of-two-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="reporting-the-results-of-two-way-anova">12.9. Reporting the results of two-way ANOVA</h2>
<ul>
<li><p>There was a significant main effect of the amount of alcohol consumed at the nightclub, on the attractiveness of the mate they selected, <em>F</em> (2, 42) = 20.07, <em>p</em> &lt; .001, <span class="math inline">\({\omega}^2\)</span>=.35. The Bonferroni <em>post hoc</em> tests revealed that the attractiveness of selected dates was significantly lower after pints than both after 2 pints and no alcohol (both <em>p</em>s &lt; .001). The attractiveness of dates after 2 pints and no alcohol were not significantly different.</p></li>
<li><p>There was a non-significant main effect of gender on the attractiveness of selected mates, <em>F</em> (1, 42) = 2.03, <em>p</em> = .161,<br>
<span class="math inline">\({\omega}^2\)</span>=.009.</p></li>
<li><p>There was a significant interaction effect between the amount of alcohol consumed and the gender of the person selecting a mate, on the attractiveness of the partner selected, <em>F</em> (2, 42) = 11.91, <em>p</em> &lt; .001, <span class="math inline">\({\omega}^2\)</span>=.20. This indicates that male and female genders were affected differently by alcohol. Specifically, the attractiveness of partners was similar in males (<em>M</em> = 66.88, <em>SD</em> = 10.33) and females (<em>M</em> = 60.63, <em>SD</em> = 4.96) after no alcohol, <em>d</em> = 0.77; the attractiveness of partners was also similar in males (<em>M</em> = 66.88, <em>SD</em> = 12.52) and females (<em>M</em> = 62.50, <em>SD</em> = 6.55) after 2 pints, <em>d</em> = 0.44; however, attractiveness of partners selected by males (<em>M</em> = 35.63, <em>SD</em> = 10.84) was significantly lower than those selected by females (<em>M</em> = 57.50, <em>SD</em> = 7.07) after 4 pints, <em>d</em> = -2.39.</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>