<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daehyeog Lee">
<meta name="dcterms.date" content="2023-01-31">

<title>Chapter 14. Mixed designs (GLM 5)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="chapter_14_files/libs/clipboard/clipboard.min.js"></script>
<script src="chapter_14_files/libs/quarto-html/quarto.js"></script>
<script src="chapter_14_files/libs/quarto-html/popper.min.js"></script>
<script src="chapter_14_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="chapter_14_files/libs/quarto-html/anchor.min.js"></script>
<link href="chapter_14_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="chapter_14_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="chapter_14_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="chapter_14_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="chapter_14_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Chapter 14. Mixed designs (GLM 5)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Daehyeog Lee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 31, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">February 13, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="what-will-this-chapter-tell-me" class="level2">
<h2 class="anchored" data-anchor-id="what-will-this-chapter-tell-me">14.1 What will this chapter tell me?</h2>
</section>
<section id="mixed-designs" class="level2">
<h2 class="anchored" data-anchor-id="mixed-designs">14.2. Mixed designs</h2>
<p><strong>Mixed design</strong>: A mixture of between-group and repeated-measures variables.</p>
<p>It is obvious that we need at least two independent variables for mixed design.</p>
</section>
<section id="what-do-men-and-women-look-for-in-a-partner" class="level2">
<h2 class="anchored" data-anchor-id="what-do-men-and-women-look-for-in-a-partner">14.3. What do men and women look for in a partner?</h2>
<p>Two repeated-measures variables: <code>looks</code>(3 levels), <code>personality</code>(3 levels)</p>
<p>One between-group variable: <code>gender</code></p>
</section>
<section id="entering-and-exploring-your-data" class="level2">
<h2 class="anchored" data-anchor-id="entering-and-exploring-your-data">14.4. Entering and exploring your data</h2>
<section id="packages-for-mixed-designs-in-r" class="level3">
<h3 class="anchored" data-anchor-id="packages-for-mixed-designs-in-r">14.4.1. Packages for mixed designs in R</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car); <span class="fu">library</span>(compute.es); <span class="fu">library</span>(effects); <span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp); <span class="fu">library</span>(pastecs); <span class="fu">library</span>(WRS2); <span class="fu">library</span>(reshape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: mvtnorm</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: survival</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: TH.data</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'TH.data'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:MASS':

    geyser</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here); <span class="fu">library</span>(ez); <span class="fu">library</span>(nlme)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /Users/leedh/self_study/discoverstat</code></pre>
</div>
</div>
</section>
<section id="general-procedure-for-mixed-designs" class="level3">
<h3 class="anchored" data-anchor-id="general-procedure-for-mixed-designs">14.4.2. General procedure for mixed designs</h3>
</section>
<section id="entering-the-data" class="level3">
<h3 class="anchored" data-anchor-id="entering-the-data">14.4.3. Entering the data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>dateData <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="fu">here</span>(<span class="st">"ch14"</span>, <span class="st">"LooksOrPersonality.dat"</span>), <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dateData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  participant gender att_high av_high ug_high att_some av_some ug_some att_none
1         P01   Male       86      84      67       88      69      50       97
2         P02   Male       91      83      53       83      74      48       86
3         P03   Male       89      88      48       99      70      48       90
4         P04   Male       89      69      58       86      77      40       87
5         P05   Male       80      81      57       88      71      50       82
6         P06   Male       80      84      51       96      63      42       92
  av_none ug_none
1      48      47
2      50      46
3      45      48
4      47      53
5      50      45
6      48      43</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>speedData <span class="ot">&lt;-</span> <span class="fu">melt</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  dateData,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="fu">c</span>(<span class="st">"participant"</span>,<span class="st">"gender"</span>),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">measured =</span> <span class="fu">c</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"att_high"</span>, <span class="st">"av_high"</span>, <span class="st">"ug_high"</span>, <span class="st">"att_some"</span>, <span class="st">"av_some"</span>, <span class="st">"ug_some"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"att_none"</span>, <span class="st">"av_none"</span>, <span class="st">"ug_none"</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(speedData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  participant gender variable value
1         P01   Male att_high    86
2         P02   Male att_high    91
3         P03   Male att_high    89
4         P04   Male att_high    89
5         P05   Male att_high    80
6         P06   Male att_high    80</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(speedData) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"participant"</span>, <span class="st">"gender"</span>, <span class="st">"groups"</span>, <span class="st">"dateRating"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(speedData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  participant gender   groups dateRating
1         P01   Male att_high         86
2         P02   Male att_high         91
3         P03   Male att_high         89
4         P04   Male att_high         89
5         P05   Male att_high         80
6         P06   Male att_high         80</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>speedData<span class="sc">$</span>personality <span class="ot">&lt;-</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gl</span>(<span class="dv">3</span>, <span class="dv">60</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Charismatic"</span>, <span class="st">"Average"</span>, <span class="st">"Dullard"</span>))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(speedData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  participant gender   groups dateRating personality
1         P01   Male att_high         86 Charismatic
2         P02   Male att_high         91 Charismatic
3         P03   Male att_high         89 Charismatic
4         P04   Male att_high         89 Charismatic
5         P05   Male att_high         80 Charismatic
6         P06   Male att_high         80 Charismatic</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>speedData<span class="sc">$</span>looks <span class="ot">&lt;-</span> <span class="fu">gl</span>(<span class="dv">3</span>, <span class="dv">20</span>, <span class="dv">180</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Attractive"</span>, <span class="st">"Average"</span>, <span class="st">"Ugly"</span>))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(speedData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  participant gender   groups dateRating personality      looks
1         P01   Male att_high         86 Charismatic Attractive
2         P02   Male att_high         91 Charismatic Attractive
3         P03   Male att_high         89 Charismatic Attractive
4         P04   Male att_high         89 Charismatic Attractive
5         P05   Male att_high         80 Charismatic Attractive
6         P06   Male att_high         80 Charismatic Attractive</code></pre>
</div>
</div>
</section>
<section id="exploring-the-data" class="level3">
<h3 class="anchored" data-anchor-id="exploring-the-data">14.4.4. Exploring the data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dateBoxplot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(speedData, <span class="fu">aes</span>(looks, dateRating, <span class="at">colour =</span> personality))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>dateBoxplot <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Attractiveness"</span>, <span class="at">y =</span> <span class="st">"Mean Rating of Date"</span>, <span class="at">colour =</span> <span class="st">"Charisma"</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter_14_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">by</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  speedData<span class="sc">$</span>dateRating,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(speedData<span class="sc">$</span>looks, speedData<span class="sc">$</span>personality, speedData<span class="sc">$</span>gender),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  stat.desc,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">basic =</span> <span class="cn">FALSE</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>: Attractive
: Charismatic
: Female
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 89.00000000  89.60000000   2.09867683   4.74753683  44.04444444   6.63659886 
    coef.var 
  0.07406918 
------------------------------------------------------------ 
: Average
: Charismatic
: Female
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 90.50000000  88.40000000   2.63396617   5.95844544  69.37777778   8.32933237 
    coef.var 
  0.09422322 
------------------------------------------------------------ 
: Ugly
: Charismatic
: Female
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 86.00000000  86.70000000   1.71949605   3.88977031  29.56666667   5.43752395 
    coef.var 
  0.06271654 
------------------------------------------------------------ 
: Attractive
: Average
: Female
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 86.00000000  87.10000000   2.15225979   4.86874991  46.32222222   6.80604307 
    coef.var 
  0.07814056 
------------------------------------------------------------ 
: Average
: Average
: Female
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 68.00000000  68.90000000   1.88237439   4.25822670  35.43333333   5.95259047 
    coef.var 
  0.08639464 
------------------------------------------------------------ 
: Ugly
: Average
: Female
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
  52.0000000   51.2000000    1.7243356    3.9007182   29.7333333    5.4528280 
    coef.var 
   0.1065005 
------------------------------------------------------------ 
: Attractive
: Dullard
: Female
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 51.50000000  51.80000000   1.09341463   2.47347574  11.95555556   3.45768066 
    coef.var 
  0.06675059 
------------------------------------------------------------ 
: Average
: Dullard
: Female
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 48.00000000  47.00000000   1.18321596   2.67662045  14.00000000   3.74165739 
    coef.var 
  0.07960973 
------------------------------------------------------------ 
: Ugly
: Dullard
: Female
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 46.50000000  46.10000000   0.97125349   2.19712803   9.43333333   3.07137320 
    coef.var 
  0.06662415 
------------------------------------------------------------ 
: Attractive
: Charismatic
: Male
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 89.00000000  88.30000000   1.80154255   4.07537238  32.45555556   5.69697776 
    coef.var 
  0.06451843 
------------------------------------------------------------ 
: Average
: Charismatic
: Male
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 84.00000000  82.80000000   2.21509970   5.01090365  49.06666667   7.00476029 
    coef.var 
  0.08459855 
------------------------------------------------------------ 
: Ugly
: Charismatic
: Male
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
   56.500000    56.800000     1.812304     4.099716    32.844444     5.731007 
    coef.var 
    0.100898 
------------------------------------------------------------ 
: Attractive
: Average
: Male
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 87.50000000  88.50000000   1.81506045   4.10595200  32.94444444   5.73972512 
    coef.var 
  0.06485565 
------------------------------------------------------------ 
: Average
: Average
: Male
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 71.00000000  71.80000000   1.39682179   3.15983042  19.51111111   4.41713834 
    coef.var 
  0.06152003 
------------------------------------------------------------ 
: Ugly
: Average
: Male
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
  48.5000000   48.3000000    1.7000000    3.8456672   28.9000000    5.3758720 
    coef.var 
   0.1113017 
------------------------------------------------------------ 
: Attractive
: Dullard
: Male
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
  86.5000000   87.3000000    1.7194961    3.8897703   29.5666667    5.4375239 
    coef.var 
   0.0622855 
------------------------------------------------------------ 
: Average
: Dullard
: Male
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 48.00000000  47.80000000   1.32329555   2.99350251  17.51111111   4.18462795 
    coef.var 
  0.08754452 
------------------------------------------------------------ 
: Ugly
: Dullard
: Male
      median         mean      SE.mean CI.mean.0.95          var      std.dev 
 45.50000000  45.80000000   1.13333333   2.56377812  12.84444444   3.58391468 
    coef.var 
  0.07825141 </code></pre>
</div>
</div>
</section>
</section>
<section id="mixed-anova" class="level2">
<h2 class="anchored" data-anchor-id="mixed-anova">14.5. Mixed ANOVA</h2>
<p>For <code>personality</code>, we could create contrasts that compare some charisma to being a dullard, and then compare the charismatic with the average date.</p>
<p>For <code>looks</code>, we could create a contrast that compares some attractiveness to being ugly, and then a second contrast that compares the attractive with the average date.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>SomevsNone <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">2</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>HivsAv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(speedData<span class="sc">$</span>personality) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(SomevsNone, HivsAv)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(speedData<span class="sc">$</span>personality)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            SomevsNone HivsAv
Charismatic          1      1
Average              1     -1
Dullard             -2      0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>AttractivevsUgly <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">2</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>AttractvsAv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(speedData<span class="sc">$</span>looks) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(AttractivevsUgly, AttractvsAv)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(speedData<span class="sc">$</span>looks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           AttractivevsUgly AttractvsAv
Attractive                1           1
Average                   1          -1
Ugly                     -2           0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>speedModel <span class="ot">&lt;-</span> <span class="fu">ezANOVA</span>(<span class="at">data =</span> speedData, <span class="at">dv =</span> .(dateRating), <span class="at">wid =</span> .(participant), <span class="at">between =</span> .(gender), <span class="at">within =</span> .(looks, personality), <span class="at">type =</span> <span class="dv">3</span>, <span class="at">detailed =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Converting "participant" to factor for ANOVA.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Converting "gender" to factor for ANOVA.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>speedModel</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$ANOVA
                    Effect DFn DFd        SSn       SSd            F
1              (Intercept)   1  18 846249.800  760.2222 2.003690e+04
2                   gender   1  18      0.200  760.2222 4.735457e-03
3                    looks   2  36  20779.633  882.7111 4.237325e+02
5              personality   2  36  23233.600 1274.0444 3.282498e+02
4             gender:looks   2  36   3944.100  882.7111 8.042699e+01
6       gender:personality   2  36   4420.133 1274.0444 6.244868e+01
7        looks:personality   4  72   4055.267 1992.6222 3.663253e+01
8 gender:looks:personality   4  72   2669.667 1992.6222 2.411596e+01
             p p&lt;.05          ges
1 7.013239e-29     * 9.942319e-01
2 9.458958e-01       4.073486e-05
3 9.594812e-26     * 8.088849e-01
5 7.689430e-24     * 8.255493e-01
4 5.234187e-14     * 4.454748e-01
6 1.974986e-12     * 4.737685e-01
7 1.101308e-16     * 4.523510e-01
8 1.107801e-12     * 3.522328e-01

$`Mauchly's Test for Sphericity`
                    Effect         W         p p&lt;.05
3                    looks 0.9602054 0.7081010      
4             gender:looks 0.9602054 0.7081010      
5              personality 0.9293298 0.5363446      
6       gender:personality 0.9293298 0.5363446      
7        looks:personality 0.6133545 0.5339382      
8 gender:looks:personality 0.6133545 0.5339382      

$`Sphericity Corrections`
                    Effect       GGe        p[GG] p[GG]&lt;.05       HFe
3                    looks 0.9617284 7.624114e-25         * 1.0744125
4             gender:looks 0.9617284 1.487026e-13         * 1.0744125
5              personality 0.9339944 2.056621e-22         * 1.0380537
6       gender:personality 0.9339944 9.442426e-12         * 1.0380537
7        looks:personality 0.7993543 9.003598e-14         * 0.9922411
8 gender:looks:personality 0.7993543 1.470422e-10         * 0.9922411
         p[HF] p[HF]&lt;.05
3 9.594812e-26         *
4 5.234187e-14         *
5 7.689430e-24         *
6 1.974986e-12         *
7 1.426883e-16         *
8 1.337876e-12         *</code></pre>
</div>
</div>
<p>The <code>looks</code>x<code>personality</code>x<code>gender</code> interaction is significant, meaning that the <code>looks</code>x<code>personality</code> interaction was significantly different in male and female participants.</p>
</section>
<section id="mixed-designs-as-a-glm" class="level2">
<h2 class="anchored" data-anchor-id="mixed-designs-as-a-glm">14.6. Mixed designs as a GLM</h2>
<p>We can extend the repeated-measures designs from the previous chapter by simply adding the between-group variable and any interaction terms as an additional predictor. When we use a multilevel model, the repeated measures are specified in the random part of the model.</p>
<section id="setting-contrasts" class="level3">
<h3 class="anchored" data-anchor-id="setting-contrasts">14.6.1. Setting contrasts</h3>
<p>If we use a multilevel model we don’t have to worry about orthogonal contrasts because we don’t need to concern ourselves with types of sums of squares in the same way that we do for ANOVA.</p>
<p>To set up this contrast as a non-orthogonal contrast, the key is that the baseline category(average attractiveness) is coded as 0 for all contrasts. Then for one of the contrasts we assign a 1 to attractive and in the other we assign a 1 to ugly. Contrast 1 compares the attractive condition to the average condition, and contrast 2 compares the ugly condition to the average condition.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>AttractivevsAv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>UglyvsAv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(speedData<span class="sc">$</span>looks) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(AttractivevsAv, UglyvsAv)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(speedData<span class="sc">$</span>looks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           AttractivevsAv UglyvsAv
Attractive              1        0
Average                 0        0
Ugly                    0        1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>HighvsAv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>DullvsAv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(speedData<span class="sc">$</span>personality) <span class="ot">&lt;-</span> <span class="fu">cbind</span>(HighvsAv, DullvsAv)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(speedData<span class="sc">$</span>personality)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            HighvsAv DullvsAv
Charismatic        1        0
Average            0        0
Dullard            0        1</code></pre>
</div>
</div>
</section>
<section id="building-the-model" class="level3">
<h3 class="anchored" data-anchor-id="building-the-model">14.6.2. Building the model</h3>
<p>We have specified the model as the outcome predicted only from the intercept (<code>dateRating ~ 1</code>), specified the relevant dataframe (<code>data = speedData</code>). The random part of the model reflects the fact that there are two repeated-measures predictors: <code>random = ~ 1|participant/looks/personality</code> tells <strong>R</strong> that the variables <strong>looks</strong> and <strong>personality</strong> are nested within the variable <strong>participant</strong>. In other words, scores for levels of these variables can be found within each participant.</p>
<p>To see the overall effect of each main effect and interaction we need to add them to the model one at a time. To add <code>looks</code> to the model we could just change the model from <code>dateRating ~ 1</code> to <code>dateRating ~ looks</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>baseline <span class="ot">&lt;-</span> <span class="fu">lme</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  dateRating <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>participant<span class="sc">/</span>looks<span class="sc">/</span>personality,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> speedData,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"ML"</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>looksM <span class="ot">&lt;-</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lme</span>(</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>    dateRating <span class="sc">~</span> looks,</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">random =</span> <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>participant<span class="sc">/</span>looks<span class="sc">/</span>personality,</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> speedData,</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"ML"</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>looksM <span class="ot">&lt;-</span> <span class="fu">update</span>(baseline, .<span class="sc">~</span>. <span class="sc">+</span> looks)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Add 'personality' and 'gender' to the model</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>personalityM <span class="ot">&lt;-</span> <span class="fu">update</span>(looksM, .<span class="sc">~</span>. <span class="sc">+</span> personality)</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>genderM <span class="ot">&lt;-</span> <span class="fu">update</span>(personalityM, .<span class="sc">~</span>. <span class="sc">+</span> gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We also need to add in the interactions between pairs of variables. There are four interactions made up from all of the combinations of the three main effects. We can add these interactions one at a time using the update command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>looks_gender <span class="ot">&lt;-</span> <span class="fu">update</span>(genderM, .<span class="sc">~</span>. <span class="sc">+</span> looks<span class="sc">:</span>gender)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>personality_gender <span class="ot">&lt;-</span> <span class="fu">update</span>(looks_gender, .<span class="sc">~</span>. <span class="sc">+</span> personality<span class="sc">:</span>gender)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>looks_personality <span class="ot">&lt;-</span> <span class="fu">update</span>(personality_gender, .<span class="sc">~</span>. <span class="sc">+</span>looks<span class="sc">:</span>personality)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>speedDateModel <span class="ot">&lt;-</span> <span class="fu">update</span>(looks_personality, .<span class="sc">~</span>. <span class="sc">+</span> looks<span class="sc">:</span>personality<span class="sc">:</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To compare these models we can list them in the order in which we want them compared in the <code>anova()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(baseline, looksM, personalityM, genderM, looks_gender, personality_gender,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>      looks_personality, speedDateModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Model df      AIC      BIC    logLik   Test   L.Ratio
baseline               1  5 1575.766 1591.730 -782.8829                 
looksM                 2  7 1511.468 1533.819 -748.7343 1 vs 2  68.29719
personalityM           3  9 1376.704 1405.441 -679.3520 2 vs 3 138.76442
genderM                4 10 1378.702 1410.632 -679.3511 3 vs 4   0.00180
looks_gender           5 12 1343.161 1381.477 -659.5808 4 vs 5  39.54079
personality_gender     6 14 1289.198 1333.899 -630.5988 5 vs 6  57.96394
looks_personality      7 18 1220.057 1277.530 -592.0283 6 vs 7  77.14102
speedDateModel         8 22 1148.462 1218.707 -552.2309 7 vs 8  79.59473
                   p-value
baseline                  
looksM              &lt;.0001
personalityM        &lt;.0001
genderM             0.9662
looks_gender        &lt;.0001
personality_gender  &lt;.0001
looks_personality   &lt;.0001
speedDateModel      &lt;.0001</code></pre>
</div>
</div>
<p>By adding <code>looks</code> as a predictor we increase the degrees of freedom by 2 and significantly improved the model. The attractiveness of the date had a significant effect on ratings, <span class="math inline">\(\chi^2(2) = 68.30, p &lt; .0001\)</span>.</p>
<p>The degrees of freedom are increased by the number of contrasts used to code this variable. For example,</p>
<ul>
<li><p>Adding the main effect of <code>personality</code> into the model increases the degrees of freedom by 2 because the two contrasts are used to code this variable.</p></li>
<li><p>Adding <code>gender</code> into the model increases the df by 1 because it was coded with a single contrast.</p></li>
<li><p>Adding <code>personality</code>x<code>gender</code> interaction into the model increases the df by 2 because <code>personality</code> is coded with two contrasts and <code>gender</code> only one, so we get 2x1 = 2 df.</p></li>
<li><p>Adding <code>looks</code>x<code>personality</code>x<code>gender</code> interaction adds 4 degrees of freedom, because <code>personality</code> is coded with two contrasts, <code>looks</code> is also coded with two contrasts, and <code>gender</code> with only one, so we get 2x2x1 = 4 df.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(speedDateModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by maximum likelihood
  Data: speedData 
       AIC      BIC    logLik
  1148.462 1218.707 -552.2309

Random effects:
 Formula: ~1 | participant
        (Intercept)
StdDev:    1.158402

 Formula: ~1 | looks %in% participant
         (Intercept)
StdDev: 0.0005262655

 Formula: ~1 | personality %in% looks %in% participant
        (Intercept)  Residual
StdDev:     5.09089 0.1283986

Fixed effects:  dateRating ~ looks + personality + gender + looks:gender + personality:gender +      looks:personality + looks:personality:gender 
                                                   Value Std.Error  DF  t-value
(Intercept)                                         68.9  1.740866 108 39.57799
looksAttractivevsAv                                 18.2  2.400632  36  7.58134
looksUglyvsAv                                      -17.7  2.400632  36 -7.37306
personalityHighvsAv                                 19.5  2.400632 108  8.12286
personalityDullvsAv                                -21.9  2.400632 108 -9.12260
genderMale                                           2.9  2.461957  18  1.17792
looksAttractivevsAv:genderMale                      -1.5  3.395006  36 -0.44183
looksUglyvsAv:genderMale                            -5.8  3.395006  36 -1.70839
personalityHighvsAv:genderMale                      -8.5  3.395006 108 -2.50368
personalityDullvsAv:genderMale                      -2.1  3.395006 108 -0.61856
looksAttractivevsAv:personalityHighvsAv            -17.0  3.395006 108 -5.00736
looksUglyvsAv:personalityHighvsAv                   16.0  3.395006 108  4.71280
looksAttractivevsAv:personalityDullvsAv            -13.4  3.395006 108 -3.94697
looksUglyvsAv:personalityDullvsAv                   16.8  3.395006 108  4.94845
looksAttractivevsAv:personalityHighvsAv:genderMale   5.8  4.801263 108  1.20802
looksUglyvsAv:personalityHighvsAv:genderMale       -18.5  4.801263 108 -3.85315
looksAttractivevsAv:personalityDullvsAv:genderMale  36.2  4.801263 108  7.53968
looksUglyvsAv:personalityDullvsAv:genderMale         4.7  4.801263 108  0.97891
                                                   p-value
(Intercept)                                         0.0000
looksAttractivevsAv                                 0.0000
looksUglyvsAv                                       0.0000
personalityHighvsAv                                 0.0000
personalityDullvsAv                                 0.0000
genderMale                                          0.2542
looksAttractivevsAv:genderMale                      0.6613
looksUglyvsAv:genderMale                            0.0962
personalityHighvsAv:genderMale                      0.0138
personalityDullvsAv:genderMale                      0.5375
looksAttractivevsAv:personalityHighvsAv             0.0000
looksUglyvsAv:personalityHighvsAv                   0.0000
looksAttractivevsAv:personalityDullvsAv             0.0001
looksUglyvsAv:personalityDullvsAv                   0.0000
looksAttractivevsAv:personalityHighvsAv:genderMale  0.2297
looksUglyvsAv:personalityHighvsAv:genderMale        0.0002
looksAttractivevsAv:personalityDullvsAv:genderMale  0.0000
looksUglyvsAv:personalityDullvsAv:genderMale        0.3298
 Correlation: 
                                                   (Intr) lksAtA lksUgA prsnHA
looksAttractivevsAv                                -0.689                     
looksUglyvsAv                                      -0.689  0.500              
personalityHighvsAv                                -0.689  0.500  0.500       
personalityDullvsAv                                -0.689  0.500  0.500  0.500
genderMale                                         -0.707  0.488  0.488  0.488
looksAttractivevsAv:genderMale                      0.488 -0.707 -0.354 -0.354
looksUglyvsAv:genderMale                            0.488 -0.354 -0.707 -0.354
personalityHighvsAv:genderMale                      0.488 -0.354 -0.354 -0.707
personalityDullvsAv:genderMale                      0.488 -0.354 -0.354 -0.354
looksAttractivevsAv:personalityHighvsAv             0.488 -0.707 -0.354 -0.707
looksUglyvsAv:personalityHighvsAv                   0.488 -0.354 -0.707 -0.707
looksAttractivevsAv:personalityDullvsAv             0.488 -0.707 -0.354 -0.354
looksUglyvsAv:personalityDullvsAv                   0.488 -0.354 -0.707 -0.354
looksAttractivevsAv:personalityHighvsAv:genderMale -0.345  0.500  0.250  0.500
looksUglyvsAv:personalityHighvsAv:genderMale       -0.345  0.250  0.500  0.500
looksAttractivevsAv:personalityDullvsAv:genderMale -0.345  0.500  0.250  0.250
looksUglyvsAv:personalityDullvsAv:genderMale       -0.345  0.250  0.500  0.250
                                                   prsnDA gndrMl lkAA:M lkUA:M
looksAttractivevsAv                                                           
looksUglyvsAv                                                                 
personalityHighvsAv                                                           
personalityDullvsAv                                                           
genderMale                                          0.488                     
looksAttractivevsAv:genderMale                     -0.354 -0.689              
looksUglyvsAv:genderMale                           -0.354 -0.689  0.500       
personalityHighvsAv:genderMale                     -0.354 -0.689  0.500  0.500
personalityDullvsAv:genderMale                     -0.707 -0.689  0.500  0.500
looksAttractivevsAv:personalityHighvsAv            -0.354 -0.345  0.500  0.250
looksUglyvsAv:personalityHighvsAv                  -0.354 -0.345  0.250  0.500
looksAttractivevsAv:personalityDullvsAv            -0.707 -0.345  0.500  0.250
looksUglyvsAv:personalityDullvsAv                  -0.707 -0.345  0.250  0.500
looksAttractivevsAv:personalityHighvsAv:genderMale  0.250  0.488 -0.707 -0.354
looksUglyvsAv:personalityHighvsAv:genderMale        0.250  0.488 -0.354 -0.707
looksAttractivevsAv:personalityDullvsAv:genderMale  0.500  0.488 -0.707 -0.354
looksUglyvsAv:personalityDullvsAv:genderMale        0.500  0.488 -0.354 -0.707
                                                   prHA:M prDA:M lkAA:HA
looksAttractivevsAv                                                     
looksUglyvsAv                                                           
personalityHighvsAv                                                     
personalityDullvsAv                                                     
genderMale                                                              
looksAttractivevsAv:genderMale                                          
looksUglyvsAv:genderMale                                                
personalityHighvsAv:genderMale                                          
personalityDullvsAv:genderMale                      0.500               
looksAttractivevsAv:personalityHighvsAv             0.500  0.250        
looksUglyvsAv:personalityHighvsAv                   0.500  0.250  0.500 
looksAttractivevsAv:personalityDullvsAv             0.250  0.500  0.500 
looksUglyvsAv:personalityDullvsAv                   0.250  0.500  0.250 
looksAttractivevsAv:personalityHighvsAv:genderMale -0.707 -0.354 -0.707 
looksUglyvsAv:personalityHighvsAv:genderMale       -0.707 -0.354 -0.354 
looksAttractivevsAv:personalityDullvsAv:genderMale -0.354 -0.707 -0.354 
looksUglyvsAv:personalityDullvsAv:genderMale       -0.354 -0.707 -0.177 
                                                   lkUA:HA lkAA:DA lkUA:DA
looksAttractivevsAv                                                       
looksUglyvsAv                                                             
personalityHighvsAv                                                       
personalityDullvsAv                                                       
genderMale                                                                
looksAttractivevsAv:genderMale                                            
looksUglyvsAv:genderMale                                                  
personalityHighvsAv:genderMale                                            
personalityDullvsAv:genderMale                                            
looksAttractivevsAv:personalityHighvsAv                                   
looksUglyvsAv:personalityHighvsAv                                         
looksAttractivevsAv:personalityDullvsAv             0.250                 
looksUglyvsAv:personalityDullvsAv                   0.500   0.500         
looksAttractivevsAv:personalityHighvsAv:genderMale -0.354  -0.354  -0.177 
looksUglyvsAv:personalityHighvsAv:genderMale       -0.707  -0.177  -0.354 
looksAttractivevsAv:personalityDullvsAv:genderMale -0.177  -0.707  -0.354 
looksUglyvsAv:personalityDullvsAv:genderMale       -0.354  -0.354  -0.707 
                                                   lAA:HA: lUA:HA: lAA:DA:
looksAttractivevsAv                                                       
looksUglyvsAv                                                             
personalityHighvsAv                                                       
personalityDullvsAv                                                       
genderMale                                                                
looksAttractivevsAv:genderMale                                            
looksUglyvsAv:genderMale                                                  
personalityHighvsAv:genderMale                                            
personalityDullvsAv:genderMale                                            
looksAttractivevsAv:personalityHighvsAv                                   
looksUglyvsAv:personalityHighvsAv                                         
looksAttractivevsAv:personalityDullvsAv                                   
looksUglyvsAv:personalityDullvsAv                                         
looksAttractivevsAv:personalityHighvsAv:genderMale                        
looksUglyvsAv:personalityHighvsAv:genderMale        0.500                 
looksAttractivevsAv:personalityDullvsAv:genderMale  0.500   0.250         
looksUglyvsAv:personalityDullvsAv:genderMale        0.250   0.500   0.500 

Standardized Within-Group Residuals:
         Min           Q1          Med           Q3          Max 
-0.094861687 -0.014722983  0.001429649  0.012195129  0.052928296 

Number of Observations: 180
Number of Groups: 
                            participant                  looks %in% participant 
                                     20                                      60 
personality %in% looks %in% participant 
                                    180 </code></pre>
</div>
</div>
</section>
<section id="the-main-effect-of-gender" class="level3">
<h3 class="anchored" data-anchor-id="the-main-effect-of-gender">14.6.3. The main effect of gender</h3>
<p>Gender did not have a significant overall effect on ratings of the dates, <span class="math inline">\(\chi^2(1) = 0.002, p = .966\)</span>. This means that if we ignore all other variables, male participants’ ratings were basically the same as those of female participants.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>genderBar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(speedData, <span class="fu">aes</span>(gender, dateRating))</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>genderBar <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"bar"</span>, <span class="at">fill =</span> <span class="st">"White"</span>, <span class="at">colour =</span> <span class="st">"Black"</span>) <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"pointrange"</span>) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Gender"</span>, <span class="at">y =</span> <span class="st">"Mean Rating of Date"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `fun.y` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.
ℹ Please use the `fun` argument instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter_14_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-main-effect-of-looks" class="level3">
<h3 class="anchored" data-anchor-id="the-main-effect-of-looks">14.6.4. The main effect of looks</h3>
<p>The attractiveness of the date had a significant effect on ratings, <span class="math inline">\(\chi^2(2) = 68.30, p &lt; .0001\)</span>. This means that if we ignore all other variables, ratings were different for attractive, average and unattractive dates. However, we really need to look at some contrasts to find out exactly which levels are different.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>looksBar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(speedData, <span class="fu">aes</span>(looks, dateRating))</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>looksBar <span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"bar"</span>, <span class="at">fill =</span> <span class="st">"White"</span>, <span class="at">colour =</span> <span class="st">"Black"</span>) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"pointrange"</span>) <span class="sc">+</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Attractiveness"</span>, <span class="at">y =</span> <span class="st">"Mean Rating of Date"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter_14_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If we look at the output of <code>summary(speedDateModel)</code>, the first contrast <code>AttractivevsAv</code> shows that attractive dates were rated significantly higher than average dates, <span class="math inline">\(b = 18.2, t(36) = 7.58, p &lt; .001\)</span>. The second contrast <code>UglyvsAv</code> shows that average dates were rated significantly higher than ugly ones, <span class="math inline">\(b = -17.7, t(36) = -7.37, p = &lt;.001\)</span>.</p>
</section>
<section id="the-main-effect-of-personality" class="level3">
<h3 class="anchored" data-anchor-id="the-main-effect-of-personality">14.6.5. The main effect of personality</h3>
<p>There was a significant main effect of charisma, <span class="math inline">\(\chi^2(2) = 138.76, p &lt; .0001\)</span>. This effect tells us that if we ignore all other variables, ratings were different for highly charismatic, averagely charismatic and dullard people.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>charismaBar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(speedData, <span class="fu">aes</span>(personality, dateRating))</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>charismaBar <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"bar"</span>, <span class="at">fill =</span> <span class="st">"White"</span>, <span class="at">colour =</span> <span class="st">"Black"</span>) <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"pointrange"</span>) <span class="sc">+</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Charisma"</span>, <span class="at">y =</span> <span class="st">"Mean Rating of Date"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter_14_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-interaction-between-gender-and-looks" class="level3">
<h3 class="anchored" data-anchor-id="the-interaction-between-gender-and-looks">14.6.6. The interaction between <code>gender</code> and <code>looks</code></h3>
<p>There was a significant interaction between the attractiveness of the date and the gender of the participant, <span class="math inline">\(\chi^2(2) = 39.54, p &lt; .0001\)</span>. This means that the profile of ratings across dates of different attractiveness was different for men and women.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>genderLooks <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(speedData, <span class="fu">aes</span>(looks, dateRating, <span class="at">colour =</span> gender))</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>genderLooks <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="fu">aes</span>(<span class="at">group=</span> gender)) <span class="sc">+</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Attractiveness"</span>, <span class="at">y =</span> <span class="st">"Mean Rating of Date"</span>, <span class="at">colour =</span> <span class="st">"Gender"</span>) <span class="sc">+</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter_14_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In general, this interaction seems to suggest that men’s interest in dating a person is more influenced by their looks than for females. Although both males’ and females’ interest decreases as attractiveness decreases, <strong>this decrease is more pronounced for men</strong>. <strong>However, we wouldn’t normally interpret this interaction because the significant higher-order three-way interactions supersedes it.</strong></p>
<section id="looks-x-gender-interaction-1-attractive-vs.-average-male-vs.-female" class="level4">
<h4 class="anchored" data-anchor-id="looks-x-gender-interaction-1-attractive-vs.-average-male-vs.-female">14.6.6.1. Looks x Gender interaction 1: attractive vs.&nbsp;average, male vs.&nbsp;female</h4>
<p>The first contrast for the <code>looks</code>x<code>gender</code> interaction term (<code>AttractivevsAv:gender</code>) compares male and female ratings of attractive relative to average-looking dates.</p>
<ul>
<li><p><span class="math inline">\(b = -1.5, t(36) = 0.44, p = .661\)</span></p></li>
<li><p>Interpretation: The increased interest in attractive dates compared to average-looking dates found for men is not significantly more than women.</p></li>
</ul>
</section>
<section id="looks-x-gender-interaction-2-ugly-vs.-average-male-vs.-female" class="level4">
<h4 class="anchored" data-anchor-id="looks-x-gender-interaction-2-ugly-vs.-average-male-vs.-female">14.6.6.2. Looks x Gender interaction 2: ugly vs.&nbsp;average, male vs.&nbsp;female</h4>
<p>The second contrast (<code>UglyvsAv:gender</code>) compares male and female ratings of ugly relative to average-looking dates.</p>
<ul>
<li><p><span class="math inline">\(b = -5.8, t(36) = -1.71, p = .096\)</span></p></li>
<li><p>Interpretation: The decreased interest in ugly dates compared to average-looking dates found for male raters is not significantly different than for female raters.</p></li>
</ul>
</section>
</section>
<section id="the-interaction-between-gender-and-personality" class="level3">
<h3 class="anchored" data-anchor-id="the-interaction-between-gender-and-personality">14.6.7. The interaction between <code>gender</code> and <code>personality</code></h3>
<p>There was a significant interaction between the attractiveness of the date and the gender of the participant, <span class="math inline">\(\chi^2(2) = 57.96, p &lt; .0001\)</span>. This effect suggests that the profile of ratings across dates of different levels of charisma was different for men and women.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>genderCharisma <span class="ot">&lt;-</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(speedData, <span class="fu">aes</span>(personality, dateRating, <span class="at">colour =</span> gender))</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>genderCharisma <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="fu">aes</span>(<span class="at">group=</span> gender)) <span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Charisma"</span>, <span class="at">y =</span> <span class="st">"Mean Rating of Date"</span>, <span class="at">colour =</span> <span class="st">"Gender"</span>) <span class="sc">+</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter_14_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This interaction seems to suggest that women’s interest in dating a person is more influenced by their charisma than for men. Although both males’ and females’ interest decreases as charisma decreases, this decrease is more pronounced for females.</p>
<section id="personality-x-gender-interaction-1-high-vs.-some-charisma-male-vs.-female" class="level4">
<h4 class="anchored" data-anchor-id="personality-x-gender-interaction-1-high-vs.-some-charisma-male-vs.-female">14.6.7.1. Personality x Gender interaction 1: high vs.&nbsp;some charisma, male vs.&nbsp;female</h4>
<p>The first contrast for this interaction term (<code>HighvsAv:gender</code>) looks at high charisma compared to average charisma, comparing male and female scores.</p>
<ul>
<li><p><span class="math inline">\(b = -8.5, t(108) = -2.50, p = .014\)</span></p></li>
<li><p>Interpretation: The increased interest in highly charismatic dates compared to averagely charismatic dates found for women is significantly more than for men.</p></li>
</ul>
</section>
<section id="personality-x-gender-interaction-2-dullard-vs.-some-charisma-male-vs.-female" class="level4">
<h4 class="anchored" data-anchor-id="personality-x-gender-interaction-2-dullard-vs.-some-charisma-male-vs.-female">14.6.7.2. Personality x Gender interaction 2: dullard vs.&nbsp;some charisma, male vs.&nbsp;female</h4>
<p>The second contrast for this interaction term (<code>DullvsAv:gender</code>) looks at differences in male and female ratings of dullard compared to dates with average charisma.</p>
<ul>
<li><p><span class="math inline">\(b = -2.1, t(108) = -0.62, p = .538\)</span></p></li>
<li><p>Interpretation: The decreased interest in dull dates compared to averagely charismatic dates found for women is not significantly more than for men.</p></li>
</ul>
</section>
</section>
<section id="the-interaction-between-looks-and-personality" class="level3">
<h3 class="anchored" data-anchor-id="the-interaction-between-looks-and-personality">14.6.8. The interaction between <code>looks</code> and <code>personality</code></h3>
<p>There was a significant interaction between the attractiveness of the date and the charisma of the date, <span class="math inline">\(\chi^2(4) = 77.14, p &lt; .0001\)</span>. This effect tells us that the profile of ratings across dates of different levels of charisma was different for attractive, average and ugly dates. However, we wouldn’t normally interpret this interaction because the significant higher-order three-way interaction supersedes it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>looksCharisma <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(speedData, <span class="fu">aes</span>(looks, dateRating, <span class="at">colour =</span> personality))</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>looksCharisma <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="fu">aes</span>(<span class="at">group=</span> personality)) <span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Attractiveness"</span>, <span class="at">y =</span> <span class="st">"Mean Rating of Date"</span>, <span class="at">colour =</span> <span class="st">"Charisma"</span>) <span class="sc">+</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter_14_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="looks-x-personality-interaction-1-attractive-vs.-average-high-charisma-vs.-some-charisma" class="level4">
<h4 class="anchored" data-anchor-id="looks-x-personality-interaction-1-attractive-vs.-average-high-charisma-vs.-some-charisma">14.6.8.1. Looks x Personality interaction 1: attractive vs.&nbsp;average, high charisma vs.&nbsp;some charisma</h4>
<p>The first contrast for this interaction term (<code>AttractivevsAv:HighvsAv</code>) asks the question “Is the difference between high charisma and average charisma the same for attractive people and average-looking people?”</p>
<ul>
<li><p><span class="math inline">\(b = -17.0, t(108) = -5.01, p &lt; .001\)</span></p></li>
<li><p>Interpretation: As dates become less attractive there is a greater decline in interest when charisma is average compared to when charisma is high.</p></li>
</ul>
</section>
<section id="looks-x-personality-interaction-2-ugly-vs.-average-high-charisma-vs.-some-charisma" class="level4">
<h4 class="anchored" data-anchor-id="looks-x-personality-interaction-2-ugly-vs.-average-high-charisma-vs.-some-charisma">14.6.8.2. Looks x Personality interaction 2: ugly vs.&nbsp;average, high charisma vs.&nbsp;some charisma</h4>
<p>The second contrast for this interaction term (<code>UglyvsAv:HighvsAv</code>) asks the question “Is the difference between high charisma and average charisma the same for ugly people and average-looking people?”</p>
<ul>
<li><p><span class="math inline">\(b = 16.0, t(108) = 4.71, p &lt; .001\)</span></p></li>
<li><p>Interpretation: As dates become less attractive there is a greater decline in interest when charisma is low compared to when charisma is high.</p></li>
</ul>
</section>
<section id="looks-x-personality-interaction-3-attractive-vs.-average-dullard-vs.-some-charisma" class="level4">
<h4 class="anchored" data-anchor-id="looks-x-personality-interaction-3-attractive-vs.-average-dullard-vs.-some-charisma">14.6.8.3. Looks x Personality interaction 3: attractive vs.&nbsp;average, dullard vs.&nbsp;some charisma</h4>
<p>The third contrast for this interaction term (<code>AttractivevsAv:DullvsAv</code>) asks the question “Is the difference between no charisma and average charisma the same for attractive people and average-looking people?”</p>
<ul>
<li><p><span class="math inline">\(b = -13.4, t(108) = -3.95, p &lt; .001\)</span></p></li>
<li><p>Interpretation: As dates become less attractive the decline in interest is different depending on whether charisma is average or low.</p></li>
</ul>
<p><u><strong><em>However, this interaction is non-significant when we exclude the higher-order three-way interaction term (<code>looks</code>x<code>personality</code>x<code>gender</code>). This result suggest that we should not interpret main effects and interactions when a higher-order interaction is significant.</em></strong></u></p>
</section>
<section id="looks-x-personality-interaction-4-ugly-vs.-average-dullard-vs.-some-charisma" class="level4">
<h4 class="anchored" data-anchor-id="looks-x-personality-interaction-4-ugly-vs.-average-dullard-vs.-some-charisma">14.6.8.4. Looks x Personality interaction 4: ugly vs.&nbsp;average, dullard vs.&nbsp;some charisma</h4>
<p>The final contrast for this interaction term (<code>UgnlyvsAv:DullvsAv</code>) asks the question “Is the difference between no charisma and some charisma the same for ugly people and average-looking people?”</p>
<ul>
<li><p><span class="math inline">\(b = 16.8, t(108) = 4.95, p &lt; .001\)</span></p></li>
<li><p>Interpretation: As dates become less attractive the decline in interest in dates with a bit of charisma is significantly greater than for dullards.</p></li>
</ul>
</section>
</section>
<section id="the-interaction-between-looks-personality-and-gender" class="level3">
<h3 class="anchored" data-anchor-id="the-interaction-between-looks-personality-and-gender">14.6.9. The interaction between <code>looks</code>, <code>personality</code> and <code>gender</code></h3>
<p><strong>The three-way interaction tells us whether the <code>looks</code>x<code>personality</code> interaction described above is the same for men and women.</strong> Output tells us that there is a significant three-way <code>looks</code>x<code>personality</code>x<code>gender</code> interaction, <span class="math inline">\(\chi^2(4) = 79.59, p &lt; .0001\)</span>. This is the highest-order effect that is significant, and consequently, we would focus on interpreting this effect and not all the lower-order ones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>looksCharismaGender <span class="ot">&lt;-</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(speedData, <span class="fu">aes</span>(looks, dateRating, <span class="at">colour =</span> personality))</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>looksCharismaGender <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="fu">aes</span>(<span class="at">group=</span> personality)) <span class="sc">+</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Attractiveness"</span>, <span class="at">y =</span> <span class="st">"Mean Rating of Date"</span>, <span class="at">colour =</span> <span class="st">"Charisma"</span>) <span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>)) <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter_14_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Male participants focus on <code>Attractiveness</code> more than <code>Charisma</code> when rating the date, while female participants focus on <code>Charisma</code> more than <code>Attractiveness</code> when rating the date.</p>
<section id="looks-x-personality-x-gender-interaction-1-attractive-vs.-average-high-charisma-vs.-some-charisma-male-vs.-female" class="level4">
<h4 class="anchored" data-anchor-id="looks-x-personality-x-gender-interaction-1-attractive-vs.-average-high-charisma-vs.-some-charisma-male-vs.-female">14.6.9.1. Looks x Personality x Gender interaction 1: attractive vs.&nbsp;average, high charisma vs.&nbsp;some charisma, male vs.&nbsp;female</h4>
<p><strong>(2nd quadrant)</strong></p>
<p>The first contrast for this interaction term compares ratings for attractive dates to average-looking dates, when high charisma is compared to average charisma in males compared to females, <span class="math inline">\(b = 5.8, t(108) = 1.21, p = .230\)</span>. <strong>(Non-significant)</strong></p>
<p>Interpretation:</p>
<ul>
<li><p>Interest in attractive dates was the same regardless of whether they had high or average charisma. However, for average-looking dates, there was more interest when that person had high charisma rather than some charisma.</p></li>
<li><p>This <strong>pattern</strong> of results is the same in males and females.</p></li>
</ul>
</section>
<section id="looks-x-personality-x-gender-interaction-2-ugly-vs.-average-high-charisma-vs.-some-charisma-males-vs.-females" class="level4">
<h4 class="anchored" data-anchor-id="looks-x-personality-x-gender-interaction-2-ugly-vs.-average-high-charisma-vs.-some-charisma-males-vs.-females">14.6.9.2. Looks x Personality x Gender interaction 2: ugly vs.&nbsp;average, high charisma vs.&nbsp;some charisma, males vs.&nbsp;females</h4>
<p><strong>(1st quadrant)</strong></p>
<p>The second contrast for this interaction term compares interest in ugly compared to average-looking dates, when high charisma is compared to average charisma, in men compared to women, <span class="math inline">\(b = -18.5, t(108) = -3.85, p &lt; .001\)</span>. <strong>(Significant)</strong></p>
<p>Interpretation:</p>
<ul>
<li><p>For men, regardless of charisma, there is a similar reduction in interest as attractiveness declines.</p></li>
<li><p>For women, when charisma is high, there is no decline in interest as attractiveness falls. However, when charisma is average, the interest declines as attractiveness falls.</p></li>
</ul>
</section>
<section id="looks-x-personality-x-gender-interaction-3-attractive-vs.-average-dullard-vs.-some-charisma-male-vs.-female" class="level4">
<h4 class="anchored" data-anchor-id="looks-x-personality-x-gender-interaction-3-attractive-vs.-average-dullard-vs.-some-charisma-male-vs.-female">14.6.9.3. Looks x Personality x Gender interaction 3: attractive vs.&nbsp;average, dullard vs.&nbsp;some charisma, male vs.&nbsp;female</h4>
<p><strong>(3rd quadrant)</strong></p>
<p>The third contrast for this interaction term compares interest in attractive compared to average-looking dates, in men compared to women, <span class="math inline">\(b = 36.2, t(108) = 7.54, p &lt; .001\)</span>. <strong>(Significant)</strong></p>
<p>Interpretation:</p>
<ul>
<li><p>Men are equally interested in their dates regardless of their charisma, but women are much less interested in an attractive person if they are a dullard.</p></li>
<li><p>With average charisma, the reduction in interest as attractiveness goes down is about the same in men and women. However, for dates who are dullards, the decrease in interest if these dates are average-looking rather than attractive is much more dramatic in men than women.</p></li>
</ul>
</section>
<section id="looks-x-personality-x-gender-interaction-4-ugly-vs.-average-dullard-vs.-some-charisma-male-vs.-female" class="level4">
<h4 class="anchored" data-anchor-id="looks-x-personality-x-gender-interaction-4-ugly-vs.-average-dullard-vs.-some-charisma-male-vs.-female">14.6.9.4. Looks x Personality x Gender interaction 4: ugly vs.&nbsp;average, dullard vs.&nbsp;some charisma, male vs.&nbsp;female</h4>
<p><strong>(4th quadrant)</strong></p>
<p>The final contrast for this interaction term compares interest in ugly compared to average-looking dates, when comparing dullards to average charisma, in men compared to women, <span class="math inline">\(b = 4.7, t(108) = 0.98, p = .330\)</span>. <strong>(Non-significant)</strong></p>
<p>Interpretation:</p>
<ul>
<li><p>Interest in ugly dates was the same regardless of whether they had average charisma or were a dullard. However, for average-looking dates, there was more interest when that person had some charisma rather than if they were a dullard.</p></li>
<li><p>The pattern of results is similar in males and females.</p></li>
</ul>
</section>
</section>
<section id="conclusions" class="level3">
<h3 class="anchored" data-anchor-id="conclusions">14.6.10. Conclusions</h3>
<ul>
<li><p>Differences exist between men and women in terms of how they’re affected by the looks and personality of potential dates.</p>
<ul>
<li><p>Men are likely to date someone who is good-looking, regardless of their personality.</p></li>
<li><p>Women are likely to date someone who is charismatic, regardless of their looking.</p></li>
</ul></li>
<li><p>When more than two independent variables are used in a model, it yields complex interaction effects that require a great deal of concentration to interpret.</p>
<ul>
<li><p>Therefore, it is important to choose which variable’s effect to be observed.</p></li>
<li><p>Plotting graphs is a useful way to interpret the interactions.</p></li>
<li><p>Setting appropriate contrasts helps us to answer the questions we have about our data.</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="calculating-effect-sizes" class="level2">
<h2 class="anchored" data-anchor-id="calculating-effect-sizes">14.7. Calculating effect sizes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>rcontrast <span class="ot">&lt;-</span> <span class="cf">function</span>(t, df)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  {</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(t<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(t<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span>df))</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"r = "</span>, r))</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Attractive vs Average, High vs Average, M/F</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="fu">rcontrast</span>(<span class="sc">-</span><span class="fl">1.21</span>, <span class="dv">108</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "r =  0.115651032655444"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ugly vs Average, High vs Average, M/F</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rcontrast</span>(<span class="fl">3.85</span>, <span class="dv">108</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "r =  0.347393559830741"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Attractive vs Average, Dull vs Average, M/F</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rcontrast</span>(<span class="fl">7.54</span>, <span class="dv">108</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "r =  0.587252348905504"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ugly vs Average, Dull vs Average, M/F</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rcontrast</span>(<span class="fl">0.98</span>, <span class="dv">108</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "r =  0.0938840316644605"</code></pre>
</div>
</div>
</section>
<section id="reporting-the-results-of-mixed-anova" class="level2">
<h2 class="anchored" data-anchor-id="reporting-the-results-of-mixed-anova">14.8. Reporting the results of mixed ANOVA</h2>
<ul>
<li><p>There were significant main effects of the ~~</p></li>
<li><p>There were significant interaction effects of the ~~</p></li>
<li><p>Most important, the looks x personality x gender interaction was significant, <span class="math inline">\(\chi^2(4) = 79.59, p &lt; .0001\)</span>. This indicates that the looks x personality interaction described previously was different in male and female participants. Contrasts were used to break down this interaction; <strong>this contrasts compared male and females scores at each level of charisma compared to the middle category of ‘average charisma’ across each level of attractiveness compared to the category of average attractiveness.</strong><br>
The first contrast revealed ~~. It tells us that ~~.<br>
The second contrast looked for differences between ~~. It tells us that ~~.<br>
The third contrast investigated differences between ~~. It tells us that ~~.<br>
The final contrast looked for differences between ~~. It tells us that ~~.</p></li>
</ul>
</section>
<section id="robust-analysis-for-mixed-designs" class="level2">
<h2 class="anchored" data-anchor-id="robust-analysis-for-mixed-designs">14.9. Robust analysis for mixed designs</h2>
<ul>
<li><p><code>tsplit()</code> performs a two-way mixed ANOVA on trimmed means.</p></li>
<li><p><code>sppba()</code> computes the main effect of factor A of a two-way mixed design using an M-estimator and bootstrap.</p></li>
<li><p><code>sppbb()</code> computes the main effect of factor B of a two-way mixed design using an M-estimator and bootstrap</p></li>
<li><p><code>sppbi()</code> computes the A x B interaction of a two-way mixed design using an M-estimator and bootstrap.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>pictureData <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="fu">here</span>(<span class="st">"ch14"</span>, <span class="st">"ProfilePicture.dat"</span>), <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pictureData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  case relationship_status couple alone
1    1   In a Relationship      4     4
2    2   In a Relationship      4     6
3    3   In a Relationship      4     7
4    4   In a Relationship      3     5
5    5   In a Relationship      4     3
6    6   In a Relationship      2     5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>pictureData<span class="sc">$</span>row <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">17</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">23</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>profileMelt <span class="ot">&lt;-</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">melt</span>(</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>    pictureData,</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">id =</span> <span class="fu">c</span>(<span class="st">"case"</span>, <span class="st">"row"</span>, <span class="st">"relationship_status"</span>),</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">measured =</span> <span class="fu">c</span>(<span class="st">"couple"</span>, <span class="st">"alone"</span>)</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(profileMelt) <span class="ot">&lt;-</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">"case"</span>, <span class="st">"row"</span>, <span class="st">"relationship_status"</span>, <span class="st">"profile_picture"</span>, <span class="st">"friend_requests"</span>)</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(profileMelt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  case row relationship_status profile_picture friend_requests
1    1   1   In a Relationship          couple               4
2    2   2   In a Relationship          couple               4
3    3   3   In a Relationship          couple               4
4    4   4   In a Relationship          couple               3
5    5   5   In a Relationship          couple               4
6    6   6   In a Relationship          couple               2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>profileData <span class="ot">&lt;-</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cast</span>(</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    profileMelt,</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    row <span class="sc">~</span> relationship_status <span class="sc">+</span> profile_picture,</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">value =</span> <span class="st">"friend_requests"</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(profileData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  row In a Relationship_couple In a Relationship_alone Single_couple
1   1                        4                       4             6
2   2                        4                       6             3
3   3                        4                       7             4
4   4                        3                       5             4
5   5                        4                       3             3
6   6                        2                       5             3
  Single_alone
1            8
2            8
3            9
4            9
5           10
6           11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>profileData<span class="sc">$</span>row <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>profileGraph <span class="ot">&lt;-</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    profileMelt,</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(relationship_status, friend_requests, <span class="at">colour =</span> profile_picture)</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>profileGraph <span class="sc">+</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="fu">aes</span>(<span class="at">group=</span> profile_picture)) <span class="sc">+</span></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Relationship Status"</span>,</span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Friend Requests"</span>,</span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"Contents of Profile Picture"</span>) <span class="sc">+</span></span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite values (`stat_summary()`).
Removed 2 rows containing non-finite values (`stat_summary()`).
Removed 2 rows containing non-finite values (`stat_summary()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter_14_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>