---
title: "R functions dictionary"
author: "Daehyeog Lee"
format: html
editor: visual
---

## Chapter 4. Exploring Data with Graphs

`file.path()`:

`geom_boxplot()`:

`geom_density()`:

`geom_histogram()`:

`geom_line()`:

`geom_point()`:

`geom_smooth()`:

`ggplot()`:

`ggsave()`:

`labs()`:

`opts()`:

`qplot()`:

`stat_summary()`:

`Sys.getenv()`:

## Chapter 5: Exploring Assumptions

`abs()`:

`by()`:

`cbind()`:

`describe()`:

`dnorm()`:

`ifelse()`:

`is.na()`:

`leveneTest()`:

`log()`:

`log10()`:

`qplot()`:

`rowMeans()`:

`rowSums()`:

`round()`:

`shapiro.test()`:

`source()`:

`sqrt()`:

`stat.desc()`:

`stat_function()`:

`tapply()`:

## Chapter 6: Correlation

`boot()`:

`boot.ci()`:

`cor()`:

`cor.test()`:

`pcor()`:

`pcor.test()`:

`polyserial()`:

`prop.table()`:

`rcorr()`:

`read.csv()`:

`read.delim()`:

`table()`:

## Chapter 7: Regression

`anova()`:

`confint()`:

`contrasts()`:

`contr.treatment()`:

`cooks.distance()`:

`covratio()`:

`coef()`:

`dfbeta()`:

`dffits()`:

`durbinWatsonTest()`:

`dwt()`:

`hatvalues()`:

`hist()`:

`lm()`:

`lm.beta()`:

`mean()`:

`plot()`:

`resid()`:

`return()`:

`rstandard()`:

`rstudent()`:

`sqrt()`:

`sum()`:

`summary()`:

`update()`:

`vif()`:

## Chapter 8. Logistic Regression

`anova()`:

`as.factor()`:

`binomial()`:

`confint()`:

`dfbeta()`:

`dffits()`:

`exp()`:

`factor()`:

`fitted()`:

`function()`:

`glm()`:

`hatvalues()`:

`head()`:

`is.factor()`:

`log()`:

`mlogit()`:

`mlogit.data()`:

`pchisq()`:

`relevel()`:

`rstandard()`:

`rstudent()`:

`summary()`:

`vif()`:
